python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_udid.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_auth.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/app.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_character.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_situation.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_deck.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_story.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_practice_ticket.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_bonds.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_band_rank.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_band_story.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_item.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_commons_live2d.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_episode.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_append_parameter.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_music_inventory.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_costume.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_after_live_talk.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/newly_opened_content.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_area_item.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_resource_count.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_live_boost.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_exchanges.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_gacha_ticket.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_gacha_status.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_area_status.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/master_player_resource.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_login_bonus.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_home_banner.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_stamp.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_degree.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_bad_penalty.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_character_profile_live2d.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_event_exchanges.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_event_item_list.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_purchase.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_mission.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_generic_story.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_live_boost_recovery_item.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_high_score_rating.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_season.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_qualify_tournament_music_score.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_event_story.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/master_event.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/master_event_story.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/master_event_character.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_event_story_memorial.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_miracle_ticket.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_miracle_ticket_exchanges.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_special_lottery_draw_result.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_music_score.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_music_achievement.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_birthday_story.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_comment_banner.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_title.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_generic_animation.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_music_shop.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_select_new_year_card.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_gacha_count_ceiling.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_backstage_talk_set.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_new_music_introduction.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_new_situation_introduction.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_friend.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_profile_situation.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_profile_degree.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_deco_frame_inventory.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_deco_pins_inventory.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_deco_equipment.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_music_video_inventory.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_purchase_menu_last_visit.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_skin.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_event_music_score.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_event_music_achievement.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/master_event_box_gacha_detail.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_event_box_gacha.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_monthly_purchase.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_subscription.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_matching_bonus.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_daily_live.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_daily_live_total_reward_history.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_comeback_status.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_graphical_information.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_multi_live_count_reward.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_digest_story.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_live_boost_use_bonus_limit_list.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_receivable_present_location_list.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_birthday_introduction.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_team_live_festival_event.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_limited_exchanges.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_add_music_difficulty_introduction.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_gallery.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_deck_rating.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/updated_band_deck_rank.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_stage_challenge.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_star_seal.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_auto_live.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_monthly_mission.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_monthly_mission_reward.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/suite_user.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/suite_user_login_bonus.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/server_system.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_area.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_action_set_album.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/user_story_event.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/suite_user_event_story_memorial.proto
python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/suite_user_character.proto

rem python -m grpc_tools.protoc -Ikrdori/pb2=krdori/protos --python_out=. krdori/protos/ce/suite_user_story.proto
