# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: krdori/pb2/ce/app.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17krdori/pb2/ce/app.proto\x12\rkrdori.pb2.ce\"\xe3\x01\n\x0e\x41ppGetResponse\x12\x16\n\x0e\x63lient_version\x18\x01 \x01(\t\x12\x14\n\x0c\x64\x61ta_version\x18\x02 \x01(\t\x12\x12\n\napp_status\x18\x03 \x01(\t\x12\x15\n\rclient_status\x18\x04 \x01(\t\x12\x0e\n\x06schema\x18\x05 \x01(\t\x12\r\n\x05gacha\x18\x07 \x01(\t\x12\x12\n\nmulti_live\x18\x08 \x01(\t\x12\x11\n\tstar_shop\x18\t \x01(\t\x12\x1b\n\x13master_data_version\x18\n \x01(\t\x12\x15\n\rphoton_app_id\x18\x0b \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'krdori.pb2.ce.app_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_APPGETRESPONSE']._serialized_start=43
  _globals['_APPGETRESPONSE']._serialized_end=270
# @@protoc_insertion_point(module_scope)
