# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: krdori/pb2/ce/master_player_resource.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*krdori/pb2/ce/master_player_resource.proto\x12\rkrdori.pb2.ce\"`\n\x0ePlayerResource\x12\x13\n\x0bresource_id\x18\x01 \x01(\r\x12\x15\n\rresource_type\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\r\x12\x10\n\x08lb_bonus\x18\x04 \x01(\r\"D\n\x12PlayerResourceList\x12.\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x1d.krdori.pb2.ce.PlayerResourceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'krdori.pb2.ce.master_player_resource_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PLAYERRESOURCE']._serialized_start=61
  _globals['_PLAYERRESOURCE']._serialized_end=157
  _globals['_PLAYERRESOURCELIST']._serialized_start=159
  _globals['_PLAYERRESOURCELIST']._serialized_end=227
# @@protoc_insertion_point(module_scope)
