# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: krdori/pb2/ce/master_event_story.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&krdori/pb2/ce/master_event_story.proto\x12\rkrdori.pb2.ce\"\x8b\x02\n\x10MasterEventStory\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\r\x12\x0b\n\x03seq\x18\x02 \x01(\r\x12\x0f\n\x07\x63\x61ption\x18\x03 \x01(\t\x12\r\n\x05title\x18\x04 \x01(\t\x12\x10\n\x08synopsis\x18\x05 \x01(\t\x12\x13\n\x0bscenario_id\x18\x06 \x01(\t\x12\x13\n\x0b\x63over_image\x18\x07 \x01(\t\x12\x18\n\x10\x62\x61\x63kground_image\x18\x08 \x01(\t\x12\x12\n\nrelease_pt\x18\t \x01(\x04\x12\x1a\n\x12release_conditions\x18\n \x01(\t\x12\x15\n\rband_story_id\x18\x0b \x01(\r\x12\x1b\n\x13\x62\x61\x63kground_image_id\x18\x0c \x01(\r\"H\n\x14MasterEventStoryList\x12\x30\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x1f.krdori.pb2.ce.MasterEventStoryb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'krdori.pb2.ce.master_event_story_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MASTEREVENTSTORY']._serialized_start=58
  _globals['_MASTEREVENTSTORY']._serialized_end=325
  _globals['_MASTEREVENTSTORYLIST']._serialized_start=327
  _globals['_MASTEREVENTSTORYLIST']._serialized_end=399
# @@protoc_insertion_point(module_scope)
