# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: krdori/pb2/ce/master_event_box_gacha_detail.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1krdori/pb2/ce/master_event_box_gacha_detail.proto\x12\rkrdori.pb2.ce\"\xbe\x01\n\x19MasterEventBoxGachaDetail\x12\x1a\n\x12\x65vent_box_gacha_id\x18\x01 \x01(\r\x12\r\n\x05round\x18\x02 \x01(\r\x12\x0b\n\x03seq\x18\x03 \x01(\r\x12\r\n\x05\x63ount\x18\x04 \x01(\r\x12\x15\n\rresource_type\x18\x05 \x01(\t\x12\x13\n\x0bresource_id\x18\x06 \x01(\r\x12\x19\n\x11resource_quantity\x18\x07 \x01(\r\x12\x13\n\x0bpickup_flag\x18\x08 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'krdori.pb2.ce.master_event_box_gacha_detail_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MASTEREVENTBOXGACHADETAIL']._serialized_start=69
  _globals['_MASTEREVENTBOXGACHADETAIL']._serialized_end=259
# @@protoc_insertion_point(module_scope)
