# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: krdori/pb2/ce/master_event.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n krdori/pb2/ce/master_event.proto\x12\rkrdori.pb2.ce\"\xf4\x02\n\x0bMasterEvent\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\r\x12\x12\n\nevent_type\x18\x02 \x01(\t\x12\x12\n\nevent_name\x18\x03 \x01(\t\x12\x19\n\x11\x61sset_bundle_name\x18\x04 \x01(\t\x12\x10\n\x08start_at\x18\x05 \x01(\x04\x12\x0e\n\x06\x65nd_at\x18\x06 \x01(\x04\x12\x12\n\nenable_flg\x18\x07 \x01(\x08\x12\x17\n\x0fpublic_start_at\x18\x08 \x01(\x04\x12\x15\n\rpublic_end_at\x18\t \x01(\x04\x12\x1d\n\x15\x64istribution_start_at\x18\n \x01(\x04\x12\x1b\n\x13\x64istribution_end_at\x18\x0b \x01(\x04\x12\x1d\n\x15\x62gm_asset_bundle_name\x18\x0c \x01(\t\x12\x15\n\rbgm_file_name\x18\r \x01(\t\x12\x18\n\x10\x61ggregate_end_at\x18\x0e \x01(\x04\x12\x1e\n\x16\x65vent_exchanges_end_at\x18\x0f \x01(\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'krdori.pb2.ce.master_event_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MASTEREVENT']._serialized_start=52
  _globals['_MASTEREVENT']._serialized_end=424
# @@protoc_insertion_point(module_scope)
