# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: krdori/pb2/ce/master_event_character.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*krdori/pb2/ce/master_event_character.proto\x12\rkrdori.pb2.ce\"\\\n\x14MasterEventCharacter\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\r\x12\x14\n\x0c\x63haracter_id\x18\x02 \x01(\r\x12\x0f\n\x07percent\x18\x03 \x01(\x02\x12\x0b\n\x03seq\x18\x04 \x01(\r\"P\n\x18MasterEventCharacterList\x12\x34\n\x07\x65ntries\x18\x01 \x03(\x0b\x32#.krdori.pb2.ce.MasterEventCharacter\"\xc0\x01\n\x1bMasterEventCharacterListMap\x12H\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x37.krdori.pb2.ce.MasterEventCharacterListMap.EntriesEntry\x1aW\n\x0c\x45ntriesEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\x36\n\x05value\x18\x02 \x01(\x0b\x32\'.krdori.pb2.ce.MasterEventCharacterList:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'krdori.pb2.ce.master_event_character_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _MASTEREVENTCHARACTERLISTMAP_ENTRIESENTRY._options = None
  _MASTEREVENTCHARACTERLISTMAP_ENTRIESENTRY._serialized_options = b'8\001'
  _globals['_MASTEREVENTCHARACTER']._serialized_start=61
  _globals['_MASTEREVENTCHARACTER']._serialized_end=153
  _globals['_MASTEREVENTCHARACTERLIST']._serialized_start=155
  _globals['_MASTEREVENTCHARACTERLIST']._serialized_end=235
  _globals['_MASTEREVENTCHARACTERLISTMAP']._serialized_start=238
  _globals['_MASTEREVENTCHARACTERLISTMAP']._serialized_end=430
  _globals['_MASTEREVENTCHARACTERLISTMAP_ENTRIESENTRY']._serialized_start=343
  _globals['_MASTEREVENTCHARACTERLISTMAP_ENTRIESENTRY']._serialized_end=430
# @@protoc_insertion_point(module_scope)
