# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: krdori/pb2/ce/newly_opened_content.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(krdori/pb2/ce/newly_opened_content.proto\x12\rkrdori.pb2.ce\"f\n\x12NewlyOpenedContent\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\x12\x14\n\x0c\x61rea_item_id\x18\x02 \x01(\r\x12\x1a\n\x12\x61rea_item_category\x18\x03 \x01(\r\x12\r\n\x05level\x18\x04 \x01(\r\"L\n\x16NewlyOpenedContentList\x12\x32\n\x07\x65ntries\x18\x01 \x03(\x0b\x32!.krdori.pb2.ce.NewlyOpenedContentb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'krdori.pb2.ce.newly_opened_content_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_NEWLYOPENEDCONTENT']._serialized_start=59
  _globals['_NEWLYOPENEDCONTENT']._serialized_end=161
  _globals['_NEWLYOPENEDCONTENTLIST']._serialized_start=163
  _globals['_NEWLYOPENEDCONTENTLIST']._serialized_end=239
# @@protoc_insertion_point(module_scope)
