# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: krdori/pb2/ce/suite_user_login_bonus.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from krdori.pb2.ce import suite_user_pb2 as krdori_dot_pb2_dot_ce_dot_suite__user__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*krdori/pb2/ce/suite_user_login_bonus.proto\x12\rkrdori.pb2.ce\x1a\x1ekrdori/pb2/ce/suite_user.proto\"e\n$SuiteUserLoginBonusAcceptAllResponse\x12=\n\x10update_resources\x18\x01 \x01(\x0b\x32#.krdori.pb2.ce.SuiteUserGetResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'krdori.pb2.ce.suite_user_login_bonus_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SUITEUSERLOGINBONUSACCEPTALLRESPONSE']._serialized_start=93
  _globals['_SUITEUSERLOGINBONUSACCEPTALLRESPONSE']._serialized_end=194
# @@protoc_insertion_point(module_scope)
