# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: krdori/pb2/ce/suite_user_event_story_memorial.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from krdori.pb2.ce import suite_user_pb2 as krdori_dot_pb2_dot_ce_dot_suite__user__pb2
from krdori.pb2.ce import user_story_event_pb2 as krdori_dot_pb2_dot_ce_dot_user__story__event__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n3krdori/pb2/ce/suite_user_event_story_memorial.proto\x12\rkrdori.pb2.ce\x1a\x1ekrdori/pb2/ce/suite_user.proto\x1a$krdori/pb2/ce/user_story_event.proto\"\xb5\x01\n\x16SuiteReadStoryResponse\x12=\n\x10update_resources\x18\x01 \x01(\x0b\x32#.krdori.pb2.ce.SuiteUserGetResponse\x12\\\n$user_story_event_read_story_response\x18\x02 \x01(\x0b\x32..krdori.pb2.ce.UserStoryEventReadStoryResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'krdori.pb2.ce.suite_user_event_story_memorial_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SUITEREADSTORYRESPONSE']._serialized_start=141
  _globals['_SUITEREADSTORYRESPONSE']._serialized_end=322
# @@protoc_insertion_point(module_scope)
