# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: krdori/pb2/ce/updated_band_deck_rank.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*krdori/pb2/ce/updated_band_deck_rank.proto\x12\rkrdori.pb2.ce\"~\n\x13UpdatedBandDeckRank\x12\x0f\n\x07\x62\x61nd_id\x18\x01 \x01(\r\x12\x15\n\rbefore_symbol\x18\x02 \x01(\t\x12\x14\n\x0c\x62\x65\x66ore_level\x18\x03 \x01(\r\x12\x14\n\x0c\x61\x66ter_symbol\x18\x04 \x01(\t\x12\x13\n\x0b\x61\x66ter_level\x18\x05 \x01(\r\"N\n\x17UpdatedBandDeckRankList\x12\x33\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\".krdori.pb2.ce.UpdatedBandDeckRankb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'krdori.pb2.ce.updated_band_deck_rank_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_UPDATEDBANDDECKRANK']._serialized_start=61
  _globals['_UPDATEDBANDDECKRANK']._serialized_end=187
  _globals['_UPDATEDBANDDECKRANKLIST']._serialized_start=189
  _globals['_UPDATEDBANDDECKRANKLIST']._serialized_end=267
# @@protoc_insertion_point(module_scope)
