# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: krdori/pb2/ce/user_select_new_year_card.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-krdori/pb2/ce/user_select_new_year_card.proto\x12\rkrdori.pb2.ce\"\xe9\x01\n\x15UserSelectNewYearCard\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\x12\x18\n\x10new_year_card_id\x18\x02 \x01(\r\x12\x0f\n\x07\x62\x61nd_id\x18\x03 \x01(\r\x12 \n\x18is_granted_new_year_card\x18\x04 \x01(\x08\x12\x1e\n\x16\x61sset_bundle_file_name\x18\x65 \x01(\t\x12%\n\x1dimage_url_for_end_of_the_year\x18\x66 \x01(\t\x12+\n#image_url_for_beginning_of_the_year\x18g \x01(\t\"\xb7\x01\n\x18UserSelectNewYearCardMap\x12\x45\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x34.krdori.pb2.ce.UserSelectNewYearCardMap.EntriesEntry\x1aT\n\x0c\x45ntriesEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\x33\n\x05value\x18\x02 \x01(\x0b\x32$.krdori.pb2.ce.UserSelectNewYearCard:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'krdori.pb2.ce.user_select_new_year_card_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _USERSELECTNEWYEARCARDMAP_ENTRIESENTRY._options = None
  _USERSELECTNEWYEARCARDMAP_ENTRIESENTRY._serialized_options = b'8\001'
  _globals['_USERSELECTNEWYEARCARD']._serialized_start=65
  _globals['_USERSELECTNEWYEARCARD']._serialized_end=298
  _globals['_USERSELECTNEWYEARCARDMAP']._serialized_start=301
  _globals['_USERSELECTNEWYEARCARDMAP']._serialized_end=484
  _globals['_USERSELECTNEWYEARCARDMAP_ENTRIESENTRY']._serialized_start=400
  _globals['_USERSELECTNEWYEARCARDMAP_ENTRIESENTRY']._serialized_end=484
# @@protoc_insertion_point(module_scope)
