# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: krdori/pb2/ce/user_item.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dkrdori/pb2/ce/user_item.proto\x12\rkrdori.pb2.ce\">\n\x08UserItem\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\x12\x0f\n\x07item_id\x18\x02 \x01(\r\x12\x10\n\x08quantity\x18\x03 \x01(\r\"8\n\x0cUserItemList\x12(\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x17.krdori.pb2.ce.UserItem\"M\n\x0fUserLimitedItem\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\x12\x17\n\x0flimited_item_id\x18\x02 \x01(\r\x12\x10\n\x08quantity\x18\x03 \x01(\r\"F\n\x13UserLimitedItemList\x12/\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x1e.krdori.pb2.ce.UserLimitedItemb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'krdori.pb2.ce.user_item_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USERITEM']._serialized_start=48
  _globals['_USERITEM']._serialized_end=110
  _globals['_USERITEMLIST']._serialized_start=112
  _globals['_USERITEMLIST']._serialized_end=168
  _globals['_USERLIMITEDITEM']._serialized_start=170
  _globals['_USERLIMITEDITEM']._serialized_end=247
  _globals['_USERLIMITEDITEMLIST']._serialized_start=249
  _globals['_USERLIMITEDITEMLIST']._serialized_end=319
# @@protoc_insertion_point(module_scope)
