# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: krdori/pb2/ce/user_friend.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fkrdori/pb2/ce/user_friend.proto\x12\rkrdori.pb2.ce\"\x88\x01\n\x12UserFriendRelation\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x18\n\x10opponent_user_id\x18\x03 \x01(\x04\x12\x19\n\x11\x66riend_updated_at\x18\x04 \x01(\x04\x12\x1c\n\x14last_changed_user_id\x18\x05 \x01(\x04\"\xae\x01\n\x15UserFriendRelationMap\x12\x42\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x31.krdori.pb2.ce.UserFriendRelationMap.EntriesEntry\x1aQ\n\x0c\x45ntriesEntry\x12\x0b\n\x03key\x18\x01 \x01(\x04\x12\x30\n\x05value\x18\x02 \x01(\x0b\x32!.krdori.pb2.ce.UserFriendRelation:\x02\x38\x01\"\x98\x02\n\x18UserFriendRelationDetail\x12=\n\x0f\x61pplication_map\x18\x01 \x01(\x0b\x32$.krdori.pb2.ce.UserFriendRelationMap\x12:\n\x0c\x61pproval_map\x18\x02 \x01(\x0b\x32$.krdori.pb2.ce.UserFriendRelationMap\x12\x38\n\nfriend_map\x18\x03 \x01(\x0b\x32$.krdori.pb2.ce.UserFriendRelationMap\x12\x19\n\x11\x61pplication_limit\x18\x04 \x01(\r\x12\x16\n\x0e\x61pproval_limit\x18\x05 \x01(\r\x12\x14\n\x0c\x66riend_limit\x18\x06 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'krdori.pb2.ce.user_friend_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _USERFRIENDRELATIONMAP_ENTRIESENTRY._options = None
  _USERFRIENDRELATIONMAP_ENTRIESENTRY._serialized_options = b'8\001'
  _globals['_USERFRIENDRELATION']._serialized_start=51
  _globals['_USERFRIENDRELATION']._serialized_end=187
  _globals['_USERFRIENDRELATIONMAP']._serialized_start=190
  _globals['_USERFRIENDRELATIONMAP']._serialized_end=364
  _globals['_USERFRIENDRELATIONMAP_ENTRIESENTRY']._serialized_start=283
  _globals['_USERFRIENDRELATIONMAP_ENTRIESENTRY']._serialized_end=364
  _globals['_USERFRIENDRELATIONDETAIL']._serialized_start=367
  _globals['_USERFRIENDRELATIONDETAIL']._serialized_end=647
# @@protoc_insertion_point(module_scope)
