# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: krdori/pb2/ce/user_mission.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n krdori/pb2/ce/user_mission.proto\x12\rkrdori.pb2.ce\"\x8a\x01\n\x0bUserMission\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\x12\x12\n\nmission_id\x18\x02 \x01(\r\x12\x0b\n\x03seq\x18\x03 \x01(\r\x12\x10\n\x08progress\x18\x04 \x01(\r\x12\x1d\n\x15mission_progress_type\x18\x05 \x01(\t\x12\x18\n\x10mission_group_id\x18\x06 \x01(\r\">\n\x0fUserMissionList\x12+\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x1a.krdori.pb2.ce.UserMission\"\xbe\x01\n\x0eUserMissionMap\x12;\n\x07\x65ntries\x18\x01 \x03(\x0b\x32*.krdori.pb2.ce.UserMissionMap.EntriesEntry\x12\x1f\n\x17limited_last_updated_at\x18\x02 \x01(\x04\x1aN\n\x0c\x45ntriesEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12-\n\x05value\x18\x02 \x01(\x0b\x32\x1e.krdori.pb2.ce.UserMissionList:\x02\x38\x01\"[\n\x15UserPanelMissionPanel\x12\x11\n\tpanel_seq\x18\x01 \x01(\r\x12\x10\n\x08progress\x18\x02 \x01(\r\x12\x1d\n\x15mission_progress_type\x18\x03 \x01(\t\"\x96\x01\n\x15UserPanelMissionBoard\x12\x11\n\tpanel_seq\x18\x01 \x01(\r\x12\x1d\n\x15mission_progress_type\x18\x02 \x01(\t\x12K\n\x1duser_panel_mission_panel_list\x18\x03 \x03(\x0b\x32$.krdori.pb2.ce.UserPanelMissionPanel\"y\n\x10UserPanelMission\x12\x18\n\x10panel_mission_id\x18\x01 \x01(\r\x12K\n\x1duser_panel_mission_board_list\x18\x02 \x03(\x0b\x32$.krdori.pb2.ce.UserPanelMissionBoard\"H\n\x14UserPanelMissionList\x12\x30\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x1f.krdori.pb2.ce.UserPanelMissionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'krdori.pb2.ce.user_mission_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _USERMISSIONMAP_ENTRIESENTRY._options = None
  _USERMISSIONMAP_ENTRIESENTRY._serialized_options = b'8\001'
  _globals['_USERMISSION']._serialized_start=52
  _globals['_USERMISSION']._serialized_end=190
  _globals['_USERMISSIONLIST']._serialized_start=192
  _globals['_USERMISSIONLIST']._serialized_end=254
  _globals['_USERMISSIONMAP']._serialized_start=257
  _globals['_USERMISSIONMAP']._serialized_end=447
  _globals['_USERMISSIONMAP_ENTRIESENTRY']._serialized_start=369
  _globals['_USERMISSIONMAP_ENTRIESENTRY']._serialized_end=447
  _globals['_USERPANELMISSIONPANEL']._serialized_start=449
  _globals['_USERPANELMISSIONPANEL']._serialized_end=540
  _globals['_USERPANELMISSIONBOARD']._serialized_start=543
  _globals['_USERPANELMISSIONBOARD']._serialized_end=693
  _globals['_USERPANELMISSION']._serialized_start=695
  _globals['_USERPANELMISSION']._serialized_end=816
  _globals['_USERPANELMISSIONLIST']._serialized_start=818
  _globals['_USERPANELMISSIONLIST']._serialized_end=890
# @@protoc_insertion_point(module_scope)
