# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: krdori/pb2/ce/user_daily_live.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#krdori/pb2/ce/user_daily_live.proto\x12\rkrdori.pb2.ce\"c\n\rUserDailyLive\x12\x17\n\x0flast_cleared_at\x18\x01 \x01(\x04\x12\x17\n\x0flive_started_at\x18\x02 \x01(\x04\x12 \n\x18get_daily_live_reward_id\x18\x03 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'krdori.pb2.ce.user_daily_live_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USERDAILYLIVE']._serialized_start=54
  _globals['_USERDAILYLIVE']._serialized_end=153
# @@protoc_insertion_point(module_scope)
