# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: krdori/pb2/ce/user_miracle_ticket.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'krdori/pb2/ce/user_miracle_ticket.proto\x12\rkrdori.pb2.ce\"j\n\x11UserMiracleTicket\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\x12\x19\n\x11miracle_ticket_id\x18\x02 \x01(\r\x12\x10\n\x08quantity\x18\x03 \x01(\r\x12\x17\n\x0f\x65xchange_end_at\x18\x04 \x01(\x04\"\xab\x01\n\x14UserMiracleTicketMap\x12\x41\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x30.krdori.pb2.ce.UserMiracleTicketMap.EntriesEntry\x1aP\n\x0c\x45ntriesEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12/\n\x05value\x18\x02 \x01(\x0b\x32 .krdori.pb2.ce.UserMiracleTicket:\x02\x38\x01\">\n+UserNotHaveViewExchangesMiracleTicketIdList\x12\x0f\n\x07\x65ntries\x18\x01 \x03(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'krdori.pb2.ce.user_miracle_ticket_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _USERMIRACLETICKETMAP_ENTRIESENTRY._options = None
  _USERMIRACLETICKETMAP_ENTRIESENTRY._serialized_options = b'8\001'
  _globals['_USERMIRACLETICKET']._serialized_start=58
  _globals['_USERMIRACLETICKET']._serialized_end=164
  _globals['_USERMIRACLETICKETMAP']._serialized_start=167
  _globals['_USERMIRACLETICKETMAP']._serialized_end=338
  _globals['_USERMIRACLETICKETMAP_ENTRIESENTRY']._serialized_start=258
  _globals['_USERMIRACLETICKETMAP_ENTRIESENTRY']._serialized_end=338
  _globals['_USERNOTHAVEVIEWEXCHANGESMIRACLETICKETIDLIST']._serialized_start=340
  _globals['_USERNOTHAVEVIEWEXCHANGESMIRACLETICKETIDLIST']._serialized_end=402
# @@protoc_insertion_point(module_scope)
