# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: krdori/pb2/ce/user_birthday_introduction.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.krdori/pb2/ce/user_birthday_introduction.proto\x12\rkrdori.pb2.ce\"]\n\x18UserBirthdayIntroduction\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\x12 \n\x18\x62irthday_introduction_id\x18\x02 \x01(\r\x12\x0e\n\x06status\x18\x03 \x01(\t\"\xc0\x01\n\x1bUserBirthdayIntroductionMap\x12H\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x37.krdori.pb2.ce.UserBirthdayIntroductionMap.EntriesEntry\x1aW\n\x0c\x45ntriesEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\x36\n\x05value\x18\x02 \x01(\x0b\x32\'.krdori.pb2.ce.UserBirthdayIntroduction:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'krdori.pb2.ce.user_birthday_introduction_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _USERBIRTHDAYINTRODUCTIONMAP_ENTRIESENTRY._options = None
  _USERBIRTHDAYINTRODUCTIONMAP_ENTRIESENTRY._serialized_options = b'8\001'
  _globals['_USERBIRTHDAYINTRODUCTION']._serialized_start=65
  _globals['_USERBIRTHDAYINTRODUCTION']._serialized_end=158
  _globals['_USERBIRTHDAYINTRODUCTIONMAP']._serialized_start=161
  _globals['_USERBIRTHDAYINTRODUCTIONMAP']._serialized_end=353
  _globals['_USERBIRTHDAYINTRODUCTIONMAP_ENTRIESENTRY']._serialized_start=266
  _globals['_USERBIRTHDAYINTRODUCTIONMAP_ENTRIESENTRY']._serialized_end=353
# @@protoc_insertion_point(module_scope)
