# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: krdori/pb2/ce/user_music_video_inventory.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.krdori/pb2/ce/user_music_video_inventory.proto\x12\rkrdori.pb2.ce\"I\n\x17UserMusicVideoInventory\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\x12\x10\n\x08music_id\x18\x02 \x01(\r\x12\x0b\n\x03seq\x18\x03 \x01(\r\"V\n\x1bUserMusicVideoInventoryList\x12\x37\n\x07\x65ntries\x18\x01 \x03(\x0b\x32&.krdori.pb2.ce.UserMusicVideoInventory\"\xc9\x01\n\x1eUserMusicVideoInventoryListMap\x12K\n\x07\x65ntries\x18\x01 \x03(\x0b\x32:.krdori.pb2.ce.UserMusicVideoInventoryListMap.EntriesEntry\x1aZ\n\x0c\x45ntriesEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\x39\n\x05value\x18\x02 \x01(\x0b\x32*.krdori.pb2.ce.UserMusicVideoInventoryList:\x02\x38\x01\"s\n\x15UserMusicVideoListMap\x12Z\n#user_music_video_inventory_list_map\x18\x01 \x01(\x0b\x32-.krdori.pb2.ce.UserMusicVideoInventoryListMapb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'krdori.pb2.ce.user_music_video_inventory_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _USERMUSICVIDEOINVENTORYLISTMAP_ENTRIESENTRY._options = None
  _USERMUSICVIDEOINVENTORYLISTMAP_ENTRIESENTRY._serialized_options = b'8\001'
  _globals['_USERMUSICVIDEOINVENTORY']._serialized_start=65
  _globals['_USERMUSICVIDEOINVENTORY']._serialized_end=138
  _globals['_USERMUSICVIDEOINVENTORYLIST']._serialized_start=140
  _globals['_USERMUSICVIDEOINVENTORYLIST']._serialized_end=226
  _globals['_USERMUSICVIDEOINVENTORYLISTMAP']._serialized_start=229
  _globals['_USERMUSICVIDEOINVENTORYLISTMAP']._serialized_end=430
  _globals['_USERMUSICVIDEOINVENTORYLISTMAP_ENTRIESENTRY']._serialized_start=340
  _globals['_USERMUSICVIDEOINVENTORYLISTMAP_ENTRIESENTRY']._serialized_end=430
  _globals['_USERMUSICVIDEOLISTMAP']._serialized_start=432
  _globals['_USERMUSICVIDEOLISTMAP']._serialized_end=547
# @@protoc_insertion_point(module_scope)
