# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: krdori/pb2/ce/user_high_score_rating.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*krdori/pb2/ce/user_high_score_rating.proto\x12\rkrdori.pb2.ce\"P\n\x18UserHighScoreMusicRating\x12\x10\n\x08music_id\x18\x01 \x01(\r\x12\x12\n\ndifficulty\x18\x02 \x01(\t\x12\x0e\n\x06rating\x18\x03 \x01(\r\"X\n\x1cUserHighScoreMusicRatingList\x12\x38\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\'.krdori.pb2.ce.UserHighScoreMusicRating\"\xc0\x01\n\x1bUserHighScoreMusicRatingMap\x12H\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x37.krdori.pb2.ce.UserHighScoreMusicRatingMap.EntriesEntry\x1aW\n\x0c\x45ntriesEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\x36\n\x05value\x18\x02 \x01(\x0b\x32\'.krdori.pb2.ce.UserHighScoreMusicRating:\x02\x38\x01\"\xfd\x05\n\x13UserHighScoreRating\x12\\\n\'user_poppin_party_high_score_music_list\x18\x01 \x01(\x0b\x32+.krdori.pb2.ce.UserHighScoreMusicRatingList\x12Y\n$user_afterglow_high_score_music_list\x18\x02 \x01(\x0b\x32+.krdori.pb2.ce.UserHighScoreMusicRatingList\x12_\n*user_pastel_palettes_high_score_music_list\x18\x03 \x01(\x0b\x32+.krdori.pb2.ce.UserHighScoreMusicRatingList\x12\x61\n,user_hello_happy_world_high_score_music_list\x18\x04 \x01(\x0b\x32+.krdori.pb2.ce.UserHighScoreMusicRatingList\x12W\n\"user_roselia_high_score_music_list\x18\x05 \x01(\x0b\x32+.krdori.pb2.ce.UserHighScoreMusicRatingList\x12U\n user_other_high_score_music_list\x18\x06 \x01(\x0b\x32+.krdori.pb2.ce.UserHighScoreMusicRatingList\x12Y\n$user_morfonica_high_score_music_list\x18\x07 \x01(\x0b\x32+.krdori.pb2.ce.UserHighScoreMusicRatingList\x12^\n)user_raise_a_suilen_high_score_music_list\x18\x08 \x01(\x0b\x32+.krdori.pb2.ce.UserHighScoreMusicRatingListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'krdori.pb2.ce.user_high_score_rating_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _USERHIGHSCOREMUSICRATINGMAP_ENTRIESENTRY._options = None
  _USERHIGHSCOREMUSICRATINGMAP_ENTRIESENTRY._serialized_options = b'8\001'
  _globals['_USERHIGHSCOREMUSICRATING']._serialized_start=61
  _globals['_USERHIGHSCOREMUSICRATING']._serialized_end=141
  _globals['_USERHIGHSCOREMUSICRATINGLIST']._serialized_start=143
  _globals['_USERHIGHSCOREMUSICRATINGLIST']._serialized_end=231
  _globals['_USERHIGHSCOREMUSICRATINGMAP']._serialized_start=234
  _globals['_USERHIGHSCOREMUSICRATINGMAP']._serialized_end=426
  _globals['_USERHIGHSCOREMUSICRATINGMAP_ENTRIESENTRY']._serialized_start=339
  _globals['_USERHIGHSCOREMUSICRATINGMAP_ENTRIESENTRY']._serialized_end=426
  _globals['_USERHIGHSCORERATING']._serialized_start=429
  _globals['_USERHIGHSCORERATING']._serialized_end=1194
# @@protoc_insertion_point(module_scope)
