# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: krdori/pb2/ce/user_multi_live_count_reward.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0krdori/pb2/ce/user_multi_live_count_reward.proto\x12\rkrdori.pb2.ce\"7\n\x18UserMultiLiveCountReward\x12\x1b\n\x13multi_live_count_id\x18\x01 \x01(\r\"X\n\x1cUserMultiLiveCountRewardList\x12\x38\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\'.krdori.pb2.ce.UserMultiLiveCountRewardb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'krdori.pb2.ce.user_multi_live_count_reward_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USERMULTILIVECOUNTREWARD']._serialized_start=67
  _globals['_USERMULTILIVECOUNTREWARD']._serialized_end=122
  _globals['_USERMULTILIVECOUNTREWARDLIST']._serialized_start=124
  _globals['_USERMULTILIVECOUNTREWARDLIST']._serialized_end=212
# @@protoc_insertion_point(module_scope)
