# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: krdori/pb2/ce/user_bonds.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1ekrdori/pb2/ce/user_bonds.proto\x12\rkrdori.pb2.ce\"L\n\tUserBonds\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\x12\x10\n\x08\x62onds_id\x18\x02 \x01(\r\x12\r\n\x05level\x18\x03 \x01(\r\x12\r\n\x05\x62onds\x18\x04 \x01(\r\":\n\rUserBondsList\x12)\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x18.krdori.pb2.ce.UserBonds\"*\n\x17UserReleasedBondsIdList\x12\x0f\n\x07\x65ntries\x18\x01 \x03(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'krdori.pb2.ce.user_bonds_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USERBONDS']._serialized_start=49
  _globals['_USERBONDS']._serialized_end=125
  _globals['_USERBONDSLIST']._serialized_start=127
  _globals['_USERBONDSLIST']._serialized_end=185
  _globals['_USERRELEASEDBONDSIDLIST']._serialized_start=187
  _globals['_USERRELEASEDBONDSIDLIST']._serialized_end=229
# @@protoc_insertion_point(module_scope)
