# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: krdori/pb2/ce/user_gacha_status.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%krdori/pb2/ce/user_gacha_status.proto\x12\rkrdori.pb2.ce\"\xa4\x01\n\x0fUserGachaStatus\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\x12\x10\n\x08gacha_id\x18\x02 \x01(\r\x12\x19\n\x11payment_method_id\x18\x03 \x01(\r\x12\x10\n\x08\x63\x61n_spin\x18\x04 \x01(\x08\x12\x16\n\x0e\x63\x61n_spin_limit\x18\x05 \x01(\r\x12\x15\n\rcan_extra_get\x18\x06 \x01(\x08\x12\x12\n\nspin_count\x18\x07 \x01(\r\"\xa5\x01\n\x12UserGachaStatusMap\x12?\n\x07\x65ntries\x18\x01 \x03(\x0b\x32..krdori.pb2.ce.UserGachaStatusMap.EntriesEntry\x1aN\n\x0c\x45ntriesEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12-\n\x05value\x18\x02 \x01(\x0b\x32\x1e.krdori.pb2.ce.UserGachaStatus:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'krdori.pb2.ce.user_gacha_status_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _USERGACHASTATUSMAP_ENTRIESENTRY._options = None
  _USERGACHASTATUSMAP_ENTRIESENTRY._serialized_options = b'8\001'
  _globals['_USERGACHASTATUS']._serialized_start=57
  _globals['_USERGACHASTATUS']._serialized_end=221
  _globals['_USERGACHASTATUSMAP']._serialized_start=224
  _globals['_USERGACHASTATUSMAP']._serialized_end=389
  _globals['_USERGACHASTATUSMAP_ENTRIESENTRY']._serialized_start=311
  _globals['_USERGACHASTATUSMAP_ENTRIESENTRY']._serialized_end=389
# @@protoc_insertion_point(module_scope)
