# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: krdori/pb2/ce/user_auth.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from krdori.pb2.ce import user_udid_pb2 as krdori_dot_pb2_dot_ce_dot_user__udid__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dkrdori/pb2/ce/user_auth.proto\x12\rkrdori.pb2.ce\x1a\x1dkrdori/pb2/ce/user_udid.proto\"M\n\x17UserAuthPrepareResponse\x12\x0f\n\x07\x61pi_key\x18\x01 \x01(\t\x12\r\n\x05nonce\x18\x02 \x01(\t\x12\x12\n\nneed_check\x18\x03 \x01(\x08\"\xd7\x01\n\x0fUserAuthRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\x12\x14\n\x0c\x64\x65vice_model\x18\x02 \x01(\t\x12%\n\x04udid\x18\x03 \x01(\x0b\x32\x17.krdori.pb2.ce.UserUdid\x12\r\n\x05hash1\x18\x04 \x01(\t\x12\x11\n\tauth_type\x18\x05 \x01(\t\x12\x1a\n\x12\x61ttestation_result\x18\x07 \x01(\t\x12\x19\n\x11\x61ttestation_error\x18\x08 \x01(\x11\x12\x1d\n\x15\x61ttestation_error_msg\x18\t \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'krdori.pb2.ce.user_auth_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USERAUTHPREPARERESPONSE']._serialized_start=79
  _globals['_USERAUTHPREPARERESPONSE']._serialized_end=156
  _globals['_USERAUTHREQUEST']._serialized_start=159
  _globals['_USERAUTHREQUEST']._serialized_end=374
# @@protoc_insertion_point(module_scope)
