# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: krdori/pb2/ce/user_deck.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dkrdori/pb2/ce/user_deck.proto\x12\rkrdori.pb2.ce\"\x95\x01\n\x08UserDeck\x12\x0f\n\x07\x64\x65\x63k_id\x18\x01 \x01(\r\x12\x11\n\tdeck_name\x18\x02 \x01(\t\x12\x0e\n\x06leader\x18\x03 \x01(\r\x12\x0f\n\x07member1\x18\x04 \x01(\r\x12\x0f\n\x07member2\x18\x05 \x01(\r\x12\x0f\n\x07member3\x18\x06 \x01(\r\x12\x0f\n\x07member4\x18\x07 \x01(\r\x12\x11\n\tdeck_type\x18\n \x01(\t\"\x90\x01\n\x0bUserDeckMap\x12\x38\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\'.krdori.pb2.ce.UserDeckMap.EntriesEntry\x1aG\n\x0c\x45ntriesEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12&\n\x05value\x18\x02 \x01(\x0b\x32\x17.krdori.pb2.ce.UserDeck:\x02\x38\x01\"8\n\x0cUserDeckList\x12(\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x17.krdori.pb2.ce.UserDeckb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'krdori.pb2.ce.user_deck_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _USERDECKMAP_ENTRIESENTRY._options = None
  _USERDECKMAP_ENTRIESENTRY._serialized_options = b'8\001'
  _globals['_USERDECK']._serialized_start=49
  _globals['_USERDECK']._serialized_end=198
  _globals['_USERDECKMAP']._serialized_start=201
  _globals['_USERDECKMAP']._serialized_end=345
  _globals['_USERDECKMAP_ENTRIESENTRY']._serialized_start=274
  _globals['_USERDECKMAP_ENTRIESENTRY']._serialized_end=345
  _globals['_USERDECKLIST']._serialized_start=347
  _globals['_USERDECKLIST']._serialized_end=403
# @@protoc_insertion_point(module_scope)
