# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: krdori/pb2/ce/user_area.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from krdori.pb2.ce import user_backstage_talk_set_pb2 as krdori_dot_pb2_dot_ce_dot_user__backstage__talk__set__pb2
from krdori.pb2.ce import user_season_pb2 as krdori_dot_pb2_dot_ce_dot_user__season__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dkrdori/pb2/ce/user_area.proto\x12\rkrdori.pb2.ce\x1a+krdori/pb2/ce/user_backstage_talk_set.proto\x1a\x1fkrdori/pb2/ce/user_season.proto\"6\n\rUserActionSet\x12\x15\n\raction_set_id\x18\x01 \x01(\r\x12\x0e\n\x06status\x18\x02 \x01(\t\"m\n\x10UserAreaResponse\x12\x0f\n\x07\x61rea_id\x18\x01 \x01(\r\x12\x31\n\x0b\x61\x63tion_sets\x18\x02 \x03(\x0b\x32\x1c.krdori.pb2.ce.UserActionSet\x12\x15\n\rarea_item_ids\x18\x03 \x03(\r\"\x98\x01\n\x0bUserAreaMap\x12\x38\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\'.krdori.pb2.ce.UserAreaMap.EntriesEntry\x1aO\n\x0c\x45ntriesEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12.\n\x05value\x18\x02 \x01(\x0b\x32\x1f.krdori.pb2.ce.UserAreaResponse:\x02\x38\x01\"\xa5\x02\n\x08UserArea\x12\x31\n\ruser_area_map\x18\x02 \x01(\x0b\x32\x1a.krdori.pb2.ce.UserAreaMap\x12I\n\tbackstage\x18\x03 \x01(\x0b\x32\x36.krdori.pb2.ce.UserLotterySelectedBackstageTalkSetList\x12.\n\x0buser_season\x18\x04 \x01(\x0b\x32\x19.krdori.pb2.ce.UserSeason\x12k\n,user_lottery_selected_backstage_talk_set_map\x18\x05 \x01(\x0b\x32\x35.krdori.pb2.ce.UserLotterySelectedBackstageTalkSetMapb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'krdori.pb2.ce.user_area_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _USERAREAMAP_ENTRIESENTRY._options = None
  _USERAREAMAP_ENTRIESENTRY._serialized_options = b'8\001'
  _globals['_USERACTIONSET']._serialized_start=126
  _globals['_USERACTIONSET']._serialized_end=180
  _globals['_USERAREARESPONSE']._serialized_start=182
  _globals['_USERAREARESPONSE']._serialized_end=291
  _globals['_USERAREAMAP']._serialized_start=294
  _globals['_USERAREAMAP']._serialized_end=446
  _globals['_USERAREAMAP_ENTRIESENTRY']._serialized_start=367
  _globals['_USERAREAMAP_ENTRIESENTRY']._serialized_end=446
  _globals['_USERAREA']._serialized_start=449
  _globals['_USERAREA']._serialized_end=742
# @@protoc_insertion_point(module_scope)
