# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: krdori/pb2/ce/user_subscription.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%krdori/pb2/ce/user_subscription.proto\x12\rkrdori.pb2.ce\"\xcc\x02\n\x10UserSubscription\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\x12\x13\n\x0bpurchase_id\x18\x02 \x01(\r\x12\x10\n\x08provider\x18\x03 \x01(\t\x12\x15\n\rpayment_count\x18\x04 \x01(\r\x12\x0e\n\x06status\x18\x05 \x01(\t\x12\x12\n\nexpired_at\x18\x06 \x01(\x04\x12\x1e\n\x16must_notify_expiration\x18\x07 \x01(\x08\x12&\n\x1emust_notify_subscription_bonus\x18\x08 \x01(\x08\x12/\n\'must_notify_other_platform_subscription\x18\t \x01(\x08\x12*\n\"must_notify_duplicate_subscription\x18\n \x01(\x08\x12 \n\x18live_boost_bonus_enabled\x18\x0b \x01(\x08\"H\n\x14UserSubscriptionList\x12\x30\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x1f.krdori.pb2.ce.UserSubscriptionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'krdori.pb2.ce.user_subscription_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USERSUBSCRIPTION']._serialized_start=57
  _globals['_USERSUBSCRIPTION']._serialized_end=389
  _globals['_USERSUBSCRIPTIONLIST']._serialized_start=391
  _globals['_USERSUBSCRIPTIONLIST']._serialized_end=463
# @@protoc_insertion_point(module_scope)
