# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: krdori/pb2/ce/user_event_story_memorial.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from krdori.pb2.ce import user_event_story_pb2 as krdori_dot_pb2_dot_ce_dot_user__event__story__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-krdori/pb2/ce/user_event_story_memorial.proto\x12\rkrdori.pb2.ce\x1a$krdori/pb2/ce/user_event_story.proto\"\x9f\x01\n\x16UserEventStoryMemorial\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\r\x12@\n\x15user_event_story_list\x18\x02 \x01(\x0b\x32!.krdori.pb2.ce.UserEventStoryList\x12\x1e\n\x16is_exist_un_read_story\x18\x03 \x01(\x08\x12\x11\n\tis_locked\x18\x04 \x01(\x08\"\xba\x01\n\x19UserEventStoryMemorialMap\x12\x46\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x35.krdori.pb2.ce.UserEventStoryMemorialMap.EntriesEntry\x1aU\n\x0c\x45ntriesEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\x34\n\x05value\x18\x02 \x01(\x0b\x32%.krdori.pb2.ce.UserEventStoryMemorial:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'krdori.pb2.ce.user_event_story_memorial_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _USEREVENTSTORYMEMORIALMAP_ENTRIESENTRY._options = None
  _USEREVENTSTORYMEMORIALMAP_ENTRIESENTRY._serialized_options = b'8\001'
  _globals['_USEREVENTSTORYMEMORIAL']._serialized_start=103
  _globals['_USEREVENTSTORYMEMORIAL']._serialized_end=262
  _globals['_USEREVENTSTORYMEMORIALMAP']._serialized_start=265
  _globals['_USEREVENTSTORYMEMORIALMAP']._serialized_end=451
  _globals['_USEREVENTSTORYMEMORIALMAP_ENTRIESENTRY']._serialized_start=366
  _globals['_USEREVENTSTORYMEMORIALMAP_ENTRIESENTRY']._serialized_end=451
# @@protoc_insertion_point(module_scope)
