# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: krdori/pb2/ce/user_commons_live2d.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'krdori/pb2/ce/user_commons_live2d.proto\x12\rkrdori.pb2.ce\"?\n\x11UserCommonsLive2d\x12\x11\n\tlive2d_id\x18\x01 \x01(\r\x12\x17\n\x0flive2d_category\x18\x02 \x01(\t\"J\n\x15UserCommonsLive2dList\x12\x31\n\x07\x65ntries\x18\x01 \x03(\x0b\x32 .krdori.pb2.ce.UserCommonsLive2d\"\xaf\x01\n\x14UserCommonsLive2dMap\x12\x41\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x30.krdori.pb2.ce.UserCommonsLive2dMap.EntriesEntry\x1aT\n\x0c\x45ntriesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x33\n\x05value\x18\x02 \x01(\x0b\x32$.krdori.pb2.ce.UserCommonsLive2dList:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'krdori.pb2.ce.user_commons_live2d_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _USERCOMMONSLIVE2DMAP_ENTRIESENTRY._options = None
  _USERCOMMONSLIVE2DMAP_ENTRIESENTRY._serialized_options = b'8\001'
  _globals['_USERCOMMONSLIVE2D']._serialized_start=58
  _globals['_USERCOMMONSLIVE2D']._serialized_end=121
  _globals['_USERCOMMONSLIVE2DLIST']._serialized_start=123
  _globals['_USERCOMMONSLIVE2DLIST']._serialized_end=197
  _globals['_USERCOMMONSLIVE2DMAP']._serialized_start=200
  _globals['_USERCOMMONSLIVE2DMAP']._serialized_end=375
  _globals['_USERCOMMONSLIVE2DMAP_ENTRIESENTRY']._serialized_start=291
  _globals['_USERCOMMONSLIVE2DMAP_ENTRIESENTRY']._serialized_end=375
# @@protoc_insertion_point(module_scope)
