# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: krdori/pb2/ce/user_title.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1ekrdori/pb2/ce/user_title.proto\x12\rkrdori.pb2.ce\"\xb7\x02\n\tUserTitle\x12\x10\n\x08title_id\x18\x01 \x01(\r\x12\x19\n\x11\x61sset_bundle_name\x18\x02 \x01(\t\x12\x17\n\x0fpublic_start_at\x18\x03 \x01(\x04\x12\x15\n\rpublic_end_at\x18\x04 \x01(\x04\x12\x1f\n\x17voice_asset_bundle_name\x18\x05 \x01(\t\x12\x12\n\ntitle_back\x18\x06 \x01(\x08\x12\x15\n\rlogo_position\x18\x07 \x01(\t\x12\x19\n\x11live2d_text_color\x18\x08 \x01(\t\x12\x1e\n\x16\x61sset_bundle_copyright\x18\t \x01(\t\x12\x1b\n\x13\x61sset_bundle_rights\x18\n \x01(\t\x12\x18\n\x10\x64isplay_priority\x18\x0b \x01(\r\x12\x0f\n\x07\x62\x61nd_id\x18\x0c \x01(\r\":\n\rUserTitleList\x12)\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x18.krdori.pb2.ce.UserTitleb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'krdori.pb2.ce.user_title_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USERTITLE']._serialized_start=50
  _globals['_USERTITLE']._serialized_end=361
  _globals['_USERTITLELIST']._serialized_start=363
  _globals['_USERTITLELIST']._serialized_end=421
# @@protoc_insertion_point(module_scope)
