# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: krdori/pb2/ce/user_team_live_festival_event.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1krdori/pb2/ce/user_team_live_festival_event.proto\x12\rkrdori.pb2.ce\"5\n\x10UserFestivalTeam\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\r\x12\x0f\n\x07team_id\x18\x02 \x01(\r\"\xa8\x01\n\x13UserFestivalTeamMap\x12@\n\x07\x65ntries\x18\x01 \x03(\x0b\x32/.krdori.pb2.ce.UserFestivalTeamMap.EntriesEntry\x1aO\n\x0c\x45ntriesEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12.\n\x05value\x18\x02 \x01(\x0b\x32\x1f.krdori.pb2.ce.UserFestivalTeam:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'krdori.pb2.ce.user_team_live_festival_event_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _USERFESTIVALTEAMMAP_ENTRIESENTRY._options = None
  _USERFESTIVALTEAMMAP_ENTRIESENTRY._serialized_options = b'8\001'
  _globals['_USERFESTIVALTEAM']._serialized_start=68
  _globals['_USERFESTIVALTEAM']._serialized_end=121
  _globals['_USERFESTIVALTEAMMAP']._serialized_start=124
  _globals['_USERFESTIVALTEAMMAP']._serialized_end=292
  _globals['_USERFESTIVALTEAMMAP_ENTRIESENTRY']._serialized_start=213
  _globals['_USERFESTIVALTEAMMAP_ENTRIESENTRY']._serialized_end=292
# @@protoc_insertion_point(module_scope)
