# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: krdori/pb2/ce/user_music_score.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$krdori/pb2/ce/user_music_score.proto\x12\rkrdori.pb2.ce\"\xa8\x01\n\x0eUserMusicScore\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\x12\x10\n\x08music_id\x18\x02 \x01(\r\x12\x18\n\x10music_difficulty\x18\x03 \x01(\t\x12\x17\n\x0fsolo_high_score\x18\x04 \x01(\r\x12\x11\n\tmax_combo\x18\x05 \x01(\r\x12\x17\n\x0fsolo_score_rank\x18\x06 \x01(\t\x12\x14\n\x0c\x63lear_status\x18\x07 \x01(\t\"D\n\x12UserMusicScoreList\x12.\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x1d.krdori.pb2.ce.UserMusicScore\"\xa6\x01\n\x11UserMusicScoreMap\x12>\n\x07\x65ntries\x18\x01 \x03(\x0b\x32-.krdori.pb2.ce.UserMusicScoreMap.EntriesEntry\x1aQ\n\x0c\x45ntriesEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\x30\n\x05value\x18\x02 \x01(\x0b\x32!.krdori.pb2.ce.UserMusicScoreList:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'krdori.pb2.ce.user_music_score_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _USERMUSICSCOREMAP_ENTRIESENTRY._options = None
  _USERMUSICSCOREMAP_ENTRIESENTRY._serialized_options = b'8\001'
  _globals['_USERMUSICSCORE']._serialized_start=56
  _globals['_USERMUSICSCORE']._serialized_end=224
  _globals['_USERMUSICSCORELIST']._serialized_start=226
  _globals['_USERMUSICSCORELIST']._serialized_end=294
  _globals['_USERMUSICSCOREMAP']._serialized_start=297
  _globals['_USERMUSICSCOREMAP']._serialized_end=463
  _globals['_USERMUSICSCOREMAP_ENTRIESENTRY']._serialized_start=382
  _globals['_USERMUSICSCOREMAP_ENTRIESENTRY']._serialized_end=463
# @@protoc_insertion_point(module_scope)
