# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: krdori/pb2/ce/user_band_story.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#krdori/pb2/ce/user_band_story.proto\x12\rkrdori.pb2.ce\"e\n\rUserBandStory\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\x12\x15\n\rband_story_id\x18\x02 \x01(\r\x12\x0f\n\x07\x62\x61nd_id\x18\x03 \x01(\r\x12\x0e\n\x06status\x18\x04 \x01(\t\x12\x0b\n\x03seq\x18\x05 \x01(\r\"B\n\x11UserBandStoryList\x12-\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x1c.krdori.pb2.ce.UserBandStoryb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'krdori.pb2.ce.user_band_story_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USERBANDSTORY']._serialized_start=54
  _globals['_USERBANDSTORY']._serialized_end=155
  _globals['_USERBANDSTORYLIST']._serialized_start=157
  _globals['_USERBANDSTORYLIST']._serialized_end=223
# @@protoc_insertion_point(module_scope)
