# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: krdori/pb2/ce/user_monthly_purchase.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)krdori/pb2/ce/user_monthly_purchase.proto\x12\rkrdori.pb2.ce\"g\n\x13UserMonthlyPurchase\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\x12\x13\n\x0bpurchase_id\x18\x02 \x01(\r\x12\x0c\n\x04year\x18\x03 \x01(\r\x12\r\n\x05month\x18\x04 \x01(\r\x12\r\n\x05\x63ount\x18\x05 \x01(\r\"\xb1\x01\n\x16UserMonthlyPurchaseMap\x12\x43\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x32.krdori.pb2.ce.UserMonthlyPurchaseMap.EntriesEntry\x1aR\n\x0c\x45ntriesEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\x31\n\x05value\x18\x02 \x01(\x0b\x32\".krdori.pb2.ce.UserMonthlyPurchase:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'krdori.pb2.ce.user_monthly_purchase_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _USERMONTHLYPURCHASEMAP_ENTRIESENTRY._options = None
  _USERMONTHLYPURCHASEMAP_ENTRIESENTRY._serialized_options = b'8\001'
  _globals['_USERMONTHLYPURCHASE']._serialized_start=60
  _globals['_USERMONTHLYPURCHASE']._serialized_end=163
  _globals['_USERMONTHLYPURCHASEMAP']._serialized_start=166
  _globals['_USERMONTHLYPURCHASEMAP']._serialized_end=343
  _globals['_USERMONTHLYPURCHASEMAP_ENTRIESENTRY']._serialized_start=261
  _globals['_USERMONTHLYPURCHASEMAP_ENTRIESENTRY']._serialized_end=343
# @@protoc_insertion_point(module_scope)
