# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: krdori/pb2/ce/user_monthly_mission_reward.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/krdori/pb2/ce/user_monthly_mission_reward.proto\x12\rkrdori.pb2.ce\"I\n\x18UserMonthlyMissionReward\x12\x19\n\x11mission_season_id\x18\x01 \x01(\r\x12\x12\n\nlive_point\x18\x02 \x01(\r\"X\n\x1cUserMonthlyMissionRewardList\x12\x38\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\'.krdori.pb2.ce.UserMonthlyMissionRewardb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'krdori.pb2.ce.user_monthly_mission_reward_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USERMONTHLYMISSIONREWARD']._serialized_start=66
  _globals['_USERMONTHLYMISSIONREWARD']._serialized_end=139
  _globals['_USERMONTHLYMISSIONREWARDLIST']._serialized_start=141
  _globals['_USERMONTHLYMISSIONREWARDLIST']._serialized_end=229
# @@protoc_insertion_point(module_scope)
