# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: krdori/pb2/ce/user_graphical_information.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.krdori/pb2/ce/user_graphical_information.proto\x12\rkrdori.pb2.ce\"0\n\x18UserGraphicalInformation\x12\x14\n\x0cgraphical_id\x18\x01 \x01(\r\"X\n\x1cUserGraphicalInformationList\x12\x38\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\'.krdori.pb2.ce.UserGraphicalInformationb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'krdori.pb2.ce.user_graphical_information_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USERGRAPHICALINFORMATION']._serialized_start=65
  _globals['_USERGRAPHICALINFORMATION']._serialized_end=113
  _globals['_USERGRAPHICALINFORMATIONLIST']._serialized_start=115
  _globals['_USERGRAPHICALINFORMATIONLIST']._serialized_end=203
# @@protoc_insertion_point(module_scope)
