# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: krdori/pb2/ce/user_music_inventory.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from krdori.pb2.ce import user_music_score_pb2 as krdori_dot_pb2_dot_ce_dot_user__music__score__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(krdori/pb2/ce/user_music_inventory.proto\x12\rkrdori.pb2.ce\x1a$krdori/pb2/ce/user_music_score.proto\"\xa7\x02\n\x12UserMusicInventory\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\x12\x10\n\x08music_id\x18\x02 \x01(\r\x12\x0b\n\x03seq\x18\x03 \x01(\r\x12>\n\x14user_music_score_map\x18\x05 \x01(\x0b\x32 .krdori.pb2.ce.UserMusicScoreMap\x12\x0e\n\x06has_mv\x18\x06 \x01(\x08\x12\x13\n\x0bis_favorite\x18\x07 \x01(\x08\x12H\n\x0c\x66\x61vorite_map\x18\x08 \x03(\x0b\x32\x32.krdori.pb2.ce.UserMusicInventory.FavoriteMapEntry\x1a\x32\n\x10\x46\x61voriteMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\x08:\x02\x38\x01\"L\n\x16UserMusicInventoryList\x12\x32\n\x07\x65ntries\x18\x01 \x03(\x0b\x32!.krdori.pb2.ce.UserMusicInventoryb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'krdori.pb2.ce.user_music_inventory_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _USERMUSICINVENTORY_FAVORITEMAPENTRY._options = None
  _USERMUSICINVENTORY_FAVORITEMAPENTRY._serialized_options = b'8\001'
  _globals['_USERMUSICINVENTORY']._serialized_start=98
  _globals['_USERMUSICINVENTORY']._serialized_end=393
  _globals['_USERMUSICINVENTORY_FAVORITEMAPENTRY']._serialized_start=343
  _globals['_USERMUSICINVENTORY_FAVORITEMAPENTRY']._serialized_end=393
  _globals['_USERMUSICINVENTORYLIST']._serialized_start=395
  _globals['_USERMUSICINVENTORYLIST']._serialized_end=471
# @@protoc_insertion_point(module_scope)
