# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: krdori/pb2/ce/user_new_situation_introduction.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n3krdori/pb2/ce/user_new_situation_introduction.proto\x12\rkrdori.pb2.ce\"f\n\x1cUserNewSituationIntroduction\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\x12%\n\x1dnew_situation_introduction_id\x18\x02 \x01(\r\x12\x0e\n\x06status\x18\x03 \x01(\t\"\xcc\x01\n\x1fUserNewSituationIntroductionMap\x12L\n\x07\x65ntries\x18\x01 \x03(\x0b\x32;.krdori.pb2.ce.UserNewSituationIntroductionMap.EntriesEntry\x1a[\n\x0c\x45ntriesEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12:\n\x05value\x18\x02 \x01(\x0b\x32+.krdori.pb2.ce.UserNewSituationIntroduction:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'krdori.pb2.ce.user_new_situation_introduction_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _USERNEWSITUATIONINTRODUCTIONMAP_ENTRIESENTRY._options = None
  _USERNEWSITUATIONINTRODUCTIONMAP_ENTRIESENTRY._serialized_options = b'8\001'
  _globals['_USERNEWSITUATIONINTRODUCTION']._serialized_start=70
  _globals['_USERNEWSITUATIONINTRODUCTION']._serialized_end=172
  _globals['_USERNEWSITUATIONINTRODUCTIONMAP']._serialized_start=175
  _globals['_USERNEWSITUATIONINTRODUCTIONMAP']._serialized_end=379
  _globals['_USERNEWSITUATIONINTRODUCTIONMAP_ENTRIESENTRY']._serialized_start=288
  _globals['_USERNEWSITUATIONINTRODUCTIONMAP_ENTRIESENTRY']._serialized_end=379
# @@protoc_insertion_point(module_scope)
