# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: krdori/pb2/ce/user_season.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fkrdori/pb2/ce/user_season.proto\x12\rkrdori.pb2.ce\"\xd9\x01\n\nUserSeason\x12\x11\n\tseason_id\x18\x01 \x01(\r\x12\x1e\n\x16season_special_id_list\x18\x02 \x03(\r\x12Y\n\x1a\x61rea_season_special_id_map\x18\x03 \x03(\x0b\x32\x35.krdori.pb2.ce.UserSeason.AreaSeasonSpecialIdMapEntry\x1a=\n\x1b\x41reaSeasonSpecialIdMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\r:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'krdori.pb2.ce.user_season_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _USERSEASON_AREASEASONSPECIALIDMAPENTRY._options = None
  _USERSEASON_AREASEASONSPECIALIDMAPENTRY._serialized_options = b'8\001'
  _globals['_USERSEASON']._serialized_start=51
  _globals['_USERSEASON']._serialized_end=268
  _globals['_USERSEASON_AREASEASONSPECIALIDMAPENTRY']._serialized_start=207
  _globals['_USERSEASON_AREASEASONSPECIALIDMAPENTRY']._serialized_end=268
# @@protoc_insertion_point(module_scope)
