# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: krdori/pb2/ce/user_skin.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dkrdori/pb2/ce/user_skin.proto\x12\rkrdori.pb2.ce\"5\n\x0cUserSkinLane\x12\x0f\n\x07user_id\x18\x01 \x01(\r\x12\x14\n\x0cskin_lane_id\x18\x02 \x01(\r\"\x9c\x01\n\x0fUserSkinLaneMap\x12<\n\x07\x65ntries\x18\x01 \x03(\x0b\x32+.krdori.pb2.ce.UserSkinLaneMap.EntriesEntry\x1aK\n\x0c\x45ntriesEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12*\n\x05value\x18\x02 \x01(\x0b\x32\x1b.krdori.pb2.ce.UserSkinLane:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'krdori.pb2.ce.user_skin_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _USERSKINLANEMAP_ENTRIESENTRY._options = None
  _USERSKINLANEMAP_ENTRIESENTRY._serialized_options = b'8\001'
  _globals['_USERSKINLANE']._serialized_start=48
  _globals['_USERSKINLANE']._serialized_end=101
  _globals['_USERSKINLANEMAP']._serialized_start=104
  _globals['_USERSKINLANEMAP']._serialized_end=260
  _globals['_USERSKINLANEMAP_ENTRIESENTRY']._serialized_start=185
  _globals['_USERSKINLANEMAP_ENTRIESENTRY']._serialized_end=260
# @@protoc_insertion_point(module_scope)
