# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: krdori/pb2/ce/user_matching_bonus.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'krdori/pb2/ce/user_matching_bonus.proto\x12\rkrdori.pb2.ce\"Y\n\x11UserMatchingBonus\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\x12\x19\n\x11matching_bonus_id\x18\x02 \x01(\r\x12\x18\n\x10matching_user_id\x18\x03 \x01(\x04\"J\n\x15UserMatchingBonusList\x12\x31\n\x07\x65ntries\x18\x01 \x03(\x0b\x32 .krdori.pb2.ce.UserMatchingBonusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'krdori.pb2.ce.user_matching_bonus_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USERMATCHINGBONUS']._serialized_start=58
  _globals['_USERMATCHINGBONUS']._serialized_end=147
  _globals['_USERMATCHINGBONUSLIST']._serialized_start=149
  _globals['_USERMATCHINGBONUSLIST']._serialized_end=223
# @@protoc_insertion_point(module_scope)
