# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: krdori/pb2/ce/user_live_boost.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#krdori/pb2/ce/user_live_boost.proto\x12\rkrdori.pb2.ce\"h\n\rUserLiveBoost\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\x12\x12\n\nlive_boost\x18\x02 \x01(\r\x12\x13\n\x0bserver_date\x18\x04 \x01(\x04\x12\x1d\n\x15live_boost_bonus_type\x18\x06 \x01(\t\"H\n\x14UserLiveBoostUseFull\x12\x1c\n\x14\x64\x61ily_use_full_count\x18\x01 \x01(\r\x12\x12\n\nreset_time\x18\x02 \x01(\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'krdori.pb2.ce.user_live_boost_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USERLIVEBOOST']._serialized_start=54
  _globals['_USERLIVEBOOST']._serialized_end=158
  _globals['_USERLIVEBOOSTUSEFULL']._serialized_start=160
  _globals['_USERLIVEBOOSTUSEFULL']._serialized_end=232
# @@protoc_insertion_point(module_scope)
