# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: krdori/pb2/ce/user_gallery.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n krdori/pb2/ce/user_gallery.proto\x12\rkrdori.pb2.ce\"@\n\x0bUserGallery\x12\x14\n\x0csituation_id\x18\x01 \x01(\r\x12\x0e\n\x06illust\x18\x02 \x01(\t\x12\x0b\n\x03seq\x18\x03 \x01(\r\">\n\x0fUserGalleryList\x12+\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x1a.krdori.pb2.ce.UserGalleryb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'krdori.pb2.ce.user_gallery_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USERGALLERY']._serialized_start=51
  _globals['_USERGALLERY']._serialized_end=115
  _globals['_USERGALLERYLIST']._serialized_start=117
  _globals['_USERGALLERYLIST']._serialized_end=179
# @@protoc_insertion_point(module_scope)
