# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: krdori/pb2/ce/user_character_profile_live2d.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1krdori/pb2/ce/user_character_profile_live2d.proto\x12\rkrdori.pb2.ce\"E\n\x1aUserCharacterProfileLive2d\x12\x14\n\x0c\x63haracter_id\x18\x01 \x01(\r\x12\x11\n\tlive2d_id\x18\x02 \x01(\r\"\\\n\x1eUserCharacterProfileLive2dList\x12:\n\x07\x65ntries\x18\x01 \x03(\x0b\x32).krdori.pb2.ce.UserCharacterProfileLive2d\"\xca\x01\n\x1dUserCharacterProfileLive2dMap\x12J\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x39.krdori.pb2.ce.UserCharacterProfileLive2dMap.EntriesEntry\x1a]\n\x0c\x45ntriesEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12<\n\x05value\x18\x02 \x01(\x0b\x32-.krdori.pb2.ce.UserCharacterProfileLive2dList:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'krdori.pb2.ce.user_character_profile_live2d_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _USERCHARACTERPROFILELIVE2DMAP_ENTRIESENTRY._options = None
  _USERCHARACTERPROFILELIVE2DMAP_ENTRIESENTRY._serialized_options = b'8\001'
  _globals['_USERCHARACTERPROFILELIVE2D']._serialized_start=68
  _globals['_USERCHARACTERPROFILELIVE2D']._serialized_end=137
  _globals['_USERCHARACTERPROFILELIVE2DLIST']._serialized_start=139
  _globals['_USERCHARACTERPROFILELIVE2DLIST']._serialized_end=231
  _globals['_USERCHARACTERPROFILELIVE2DMAP']._serialized_start=234
  _globals['_USERCHARACTERPROFILELIVE2DMAP']._serialized_end=436
  _globals['_USERCHARACTERPROFILELIVE2DMAP_ENTRIESENTRY']._serialized_start=343
  _globals['_USERCHARACTERPROFILELIVE2DMAP_ENTRIESENTRY']._serialized_end=436
# @@protoc_insertion_point(module_scope)
