# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: krdori/pb2/ce/user_comment_banner.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'krdori/pb2/ce/user_comment_banner.proto\x12\rkrdori.pb2.ce\"\xb9\x02\n\x11UserCommentBanner\x12\x19\n\x11\x61sset_bundle_name\x18\x01 \x01(\t\x12\x14\n\x0cpublished_at\x18\x02 \x01(\x04\x12\x11\n\tclosed_at\x18\x03 \x01(\x04\x12\x0b\n\x03url\x18\x04 \x01(\t\x12\x0f\n\x07\x63omment\x18\x05 \x01(\t\x12\x19\n\x11transition_method\x18\x06 \x01(\t\x12\x19\n\x11\x63omment_banner_id\x18\x07 \x01(\r\x12\x17\n\x0fis_once_comment\x18\x08 \x01(\x08\x12\x15\n\rtransition_id\x18\t \x01(\r\x12\x19\n\x11release_rank_from\x18\n \x01(\r\x12\x17\n\x0frelease_rank_to\x18\x0b \x01(\r\x12\x11\n\ticon_type\x18\x0c \x01(\t\x12\x15\n\ricon_view_flg\x18\r \x01(\x08\"J\n\x15UserCommentBannerList\x12\x31\n\x07\x65ntries\x18\x01 \x03(\x0b\x32 .krdori.pb2.ce.UserCommentBannerb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'krdori.pb2.ce.user_comment_banner_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USERCOMMENTBANNER']._serialized_start=59
  _globals['_USERCOMMENTBANNER']._serialized_end=372
  _globals['_USERCOMMENTBANNERLIST']._serialized_start=374
  _globals['_USERCOMMENTBANNERLIST']._serialized_end=448
# @@protoc_insertion_point(module_scope)
