# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: krdori/pb2/ce/user_event_box_gacha.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from krdori.pb2.ce import master_event_box_gacha_detail_pb2 as krdori_dot_pb2_dot_ce_dot_master__event__box__gacha__detail__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(krdori/pb2/ce/user_event_box_gacha.proto\x12\rkrdori.pb2.ce\x1a\x31krdori/pb2/ce/master_event_box_gacha_detail.proto\"<\n\x17UserEventBoxGachaRemain\x12\x0b\n\x03seq\x18\x01 \x01(\r\x12\x14\n\x0cremain_count\x18\x02 \x01(\r\"\x88\x02\n\x11UserEventBoxGacha\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\x12\x1a\n\x12\x65vent_box_gacha_id\x18\x02 \x01(\r\x12\r\n\x05round\x18\x03 \x01(\r\x12\x37\n\x07remains\x18\x65 \x03(\x0b\x32&.krdori.pb2.ce.UserEventBoxGachaRemain\x12?\n\rpickup_detail\x18\x66 \x01(\x0b\x32(.krdori.pb2.ce.MasterEventBoxGachaDetail\x12=\n\rpickup_remain\x18g \x01(\x0b\x32&.krdori.pb2.ce.UserEventBoxGachaRemain\"\xab\x01\n\x14UserEventBoxGachaMap\x12\x41\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x30.krdori.pb2.ce.UserEventBoxGachaMap.EntriesEntry\x1aP\n\x0c\x45ntriesEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12/\n\x05value\x18\x02 \x01(\x0b\x32 .krdori.pb2.ce.UserEventBoxGacha:\x02\x38\x01\"M\n\x1dUserEventBoxGachaSpinSettings\x12\x15\n\rlump_spin_flg\x18\x01 \x01(\x08\x12\x15\n\rauto_stop_flg\x18\x02 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'krdori.pb2.ce.user_event_box_gacha_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _USEREVENTBOXGACHAMAP_ENTRIESENTRY._options = None
  _USEREVENTBOXGACHAMAP_ENTRIESENTRY._serialized_options = b'8\001'
  _globals['_USEREVENTBOXGACHAREMAIN']._serialized_start=110
  _globals['_USEREVENTBOXGACHAREMAIN']._serialized_end=170
  _globals['_USEREVENTBOXGACHA']._serialized_start=173
  _globals['_USEREVENTBOXGACHA']._serialized_end=437
  _globals['_USEREVENTBOXGACHAMAP']._serialized_start=440
  _globals['_USEREVENTBOXGACHAMAP']._serialized_end=611
  _globals['_USEREVENTBOXGACHAMAP_ENTRIESENTRY']._serialized_start=531
  _globals['_USEREVENTBOXGACHAMAP_ENTRIESENTRY']._serialized_end=611
  _globals['_USEREVENTBOXGACHASPINSETTINGS']._serialized_start=613
  _globals['_USEREVENTBOXGACHASPINSETTINGS']._serialized_end=690
# @@protoc_insertion_point(module_scope)
