# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: krdori/pb2/ce/user_degree.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fkrdori/pb2/ce/user_degree.proto\x12\rkrdori.pb2.ce\"0\n\nUserDegree\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\x12\x11\n\tdegree_id\x18\x02 \x01(\r\"\x96\x01\n\rUserDegreeMap\x12:\n\x07\x65ntries\x18\x01 \x03(\x0b\x32).krdori.pb2.ce.UserDegreeMap.EntriesEntry\x1aI\n\x0c\x45ntriesEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12(\n\x05value\x18\x02 \x01(\x0b\x32\x19.krdori.pb2.ce.UserDegree:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'krdori.pb2.ce.user_degree_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _USERDEGREEMAP_ENTRIESENTRY._options = None
  _USERDEGREEMAP_ENTRIESENTRY._serialized_options = b'8\001'
  _globals['_USERDEGREE']._serialized_start=50
  _globals['_USERDEGREE']._serialized_end=98
  _globals['_USERDEGREEMAP']._serialized_start=101
  _globals['_USERDEGREEMAP']._serialized_end=251
  _globals['_USERDEGREEMAP_ENTRIESENTRY']._serialized_start=178
  _globals['_USERDEGREEMAP_ENTRIESENTRY']._serialized_end=251
# @@protoc_insertion_point(module_scope)
