# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: krdori/pb2/ce/user_exchanges.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"krdori/pb2/ce/user_exchanges.proto\x12\rkrdori.pb2.ce\"X\n\rUserExchanges\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\x12\x14\n\x0c\x65xchanges_id\x18\x02 \x01(\r\x12\x0e\n\x06remain\x18\x03 \x01(\r\x12\x10\n\x08reset_at\x18\x04 \x01(\x04\"B\n\x11UserExchangesList\x12-\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x1c.krdori.pb2.ce.UserExchangesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'krdori.pb2.ce.user_exchanges_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USEREXCHANGES']._serialized_start=53
  _globals['_USEREXCHANGES']._serialized_end=141
  _globals['_USEREXCHANGESLIST']._serialized_start=143
  _globals['_USEREXCHANGESLIST']._serialized_end=209
# @@protoc_insertion_point(module_scope)
