# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: krdori/pb2/ce/user_deco_equipment.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'krdori/pb2/ce/user_deco_equipment.proto\x12\rkrdori.pb2.ce\"\xae\x01\n\x11UserDecoEquipment\x12\x0f\n\x07user_id\x18\x01 \x01(\r\x12\x15\n\rdeco_frame_id\x18\x02 \x01(\r\x12\x15\n\rdeco_pins_id1\x18\x03 \x01(\r\x12\x15\n\rdeco_pins_id2\x18\x04 \x01(\r\x12\x15\n\rdeco_pins_id3\x18\x05 \x01(\r\x12\x15\n\rdeco_pins_id4\x18\x06 \x01(\r\x12\x15\n\rdeco_pins_id5\x18\x07 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'krdori.pb2.ce.user_deco_equipment_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USERDECOEQUIPMENT']._serialized_start=59
  _globals['_USERDECOEQUIPMENT']._serialized_end=233
# @@protoc_insertion_point(module_scope)
