# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: krdori/pb2/ce/user_qualify_tournament_music_score.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7krdori/pb2/ce/user_qualify_tournament_music_score.proto\x12\rkrdori.pb2.ce\"\x8d\x02\n\x1fUserQualifyTournamentMusicScore\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\x12\x1d\n\x15qualify_tournament_id\x18\x02 \x01(\r\x12\x10\n\x08music_id\x18\x03 \x01(\r\x12\x18\n\x10music_difficulty\x18\x04 \x01(\t\x12\x17\n\x0fsolo_high_score\x18\x05 \x01(\r\x12\x17\n\x0fsolo_score_rank\x18\x06 \x01(\t\x12\x11\n\tmax_combo\x18\x07 \x01(\r\x12\x14\n\x0c\x63lear_status\x18\x08 \x01(\t\x12\x12\n\nplay_count\x18\t \x01(\r\x12\x1f\n\x17qualify_tournament_type\x18\n \x01(\t\"f\n#UserQualifyTournamentMusicScoreList\x12?\n\x07\x65ntries\x18\x01 \x03(\x0b\x32..krdori.pb2.ce.UserQualifyTournamentMusicScore\"\xd9\x01\n\"UserQualifyTournamentMusicScoreMap\x12O\n\x07\x65ntries\x18\x01 \x03(\x0b\x32>.krdori.pb2.ce.UserQualifyTournamentMusicScoreMap.EntriesEntry\x1a\x62\n\x0c\x45ntriesEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\x41\n\x05value\x18\x02 \x01(\x0b\x32\x32.krdori.pb2.ce.UserQualifyTournamentMusicScoreList:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'krdori.pb2.ce.user_qualify_tournament_music_score_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _USERQUALIFYTOURNAMENTMUSICSCOREMAP_ENTRIESENTRY._options = None
  _USERQUALIFYTOURNAMENTMUSICSCOREMAP_ENTRIESENTRY._serialized_options = b'8\001'
  _globals['_USERQUALIFYTOURNAMENTMUSICSCORE']._serialized_start=75
  _globals['_USERQUALIFYTOURNAMENTMUSICSCORE']._serialized_end=344
  _globals['_USERQUALIFYTOURNAMENTMUSICSCORELIST']._serialized_start=346
  _globals['_USERQUALIFYTOURNAMENTMUSICSCORELIST']._serialized_end=448
  _globals['_USERQUALIFYTOURNAMENTMUSICSCOREMAP']._serialized_start=451
  _globals['_USERQUALIFYTOURNAMENTMUSICSCOREMAP']._serialized_end=668
  _globals['_USERQUALIFYTOURNAMENTMUSICSCOREMAP_ENTRIESENTRY']._serialized_start=570
  _globals['_USERQUALIFYTOURNAMENTMUSICSCOREMAP_ENTRIESENTRY']._serialized_end=668
# @@protoc_insertion_point(module_scope)
