# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: krdori/pb2/ce/user_auto_live.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"krdori/pb2/ce/user_auto_live.proto\x12\rkrdori.pb2.ce\"E\n\x0cUserAutoLive\x12!\n\x19\x64\x61ily_auto_live_use_count\x18\x01 \x01(\r\x12\x12\n\nreset_time\x18\x02 \x01(\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'krdori.pb2.ce.user_auto_live_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USERAUTOLIVE']._serialized_start=53
  _globals['_USERAUTOLIVE']._serialized_end=122
# @@protoc_insertion_point(module_scope)
