# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: krdori/pb2/ce/user_monthly_mission.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(krdori/pb2/ce/user_monthly_mission.proto\x12\rkrdori.pb2.ce\"m\n\x12UserMonthlyMission\x12\x19\n\x11mission_season_id\x18\x01 \x01(\r\x12\x12\n\nlive_point\x18\x02 \x01(\r\x12(\n is_purchase_premium_mission_pass\x18\x03 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'krdori.pb2.ce.user_monthly_mission_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USERMONTHLYMISSION']._serialized_start=59
  _globals['_USERMONTHLYMISSION']._serialized_end=168
# @@protoc_insertion_point(module_scope)
