# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: krdori/pb2/ce/user_after_live_talk.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(krdori/pb2/ce/user_after_live_talk.proto\x12\rkrdori.pb2.ce\"M\n\x11UserAfterLiveTalk\x12\x1a\n\x12\x61\x66ter_live_talk_id\x18\x01 \x01(\r\x12\x1c\n\x14\x61\x66ter_live_talk_type\x18\x02 \x01(\t\"J\n\x15UserAfterLiveTalkList\x12\x31\n\x07\x65ntries\x18\x01 \x03(\x0b\x32 .krdori.pb2.ce.UserAfterLiveTalk\"\xb7\x01\n\x18UserAfterLiveTalkListMap\x12\x45\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x34.krdori.pb2.ce.UserAfterLiveTalkListMap.EntriesEntry\x1aT\n\x0c\x45ntriesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x33\n\x05value\x18\x02 \x01(\x0b\x32$.krdori.pb2.ce.UserAfterLiveTalkList:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'krdori.pb2.ce.user_after_live_talk_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _USERAFTERLIVETALKLISTMAP_ENTRIESENTRY._options = None
  _USERAFTERLIVETALKLISTMAP_ENTRIESENTRY._serialized_options = b'8\001'
  _globals['_USERAFTERLIVETALK']._serialized_start=59
  _globals['_USERAFTERLIVETALK']._serialized_end=136
  _globals['_USERAFTERLIVETALKLIST']._serialized_start=138
  _globals['_USERAFTERLIVETALKLIST']._serialized_end=212
  _globals['_USERAFTERLIVETALKLISTMAP']._serialized_start=215
  _globals['_USERAFTERLIVETALKLISTMAP']._serialized_end=398
  _globals['_USERAFTERLIVETALKLISTMAP_ENTRIESENTRY']._serialized_start=314
  _globals['_USERAFTERLIVETALKLISTMAP_ENTRIESENTRY']._serialized_end=398
# @@protoc_insertion_point(module_scope)
