# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: krdori/pb2/ce/user_live_boost_use_bonus_limit_list.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n8krdori/pb2/ce/user_live_boost_use_bonus_limit_list.proto\x12\rkrdori.pb2.ce\" \n\x1eUserLiveBoostUseBonusLimitListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'krdori.pb2.ce.user_live_boost_use_bonus_limit_list_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USERLIVEBOOSTUSEBONUSLIMITLIST']._serialized_start=75
  _globals['_USERLIVEBOOSTUSEBONUSLIMITLIST']._serialized_end=107
# @@protoc_insertion_point(module_scope)
