# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: krdori/pb2/ce/user_deck_rating.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$krdori/pb2/ce/user_deck_rating.proto\x12\rkrdori.pb2.ce\"\xcf\x01\n\x0eUserDeckRating\x12\x11\n\tattribute\x18\x01 \x01(\t\x12\x0e\n\x06leader\x18\x02 \x01(\r\x12\x0f\n\x07member1\x18\x03 \x01(\r\x12\x0f\n\x07member2\x18\x04 \x01(\r\x12\x0f\n\x07member3\x18\x05 \x01(\r\x12\x0f\n\x07member4\x18\x06 \x01(\r\x12\x0c\n\x04rank\x18\x07 \x01(\t\x12\r\n\x05score\x18\x08 \x01(\r\x12\r\n\x05level\x18\t \x01(\r\x12\x14\n\x0clower_rating\x18\n \x01(\r\x12\x14\n\x0cupper_rating\x18\x0b \x01(\r\"m\n\x13UserDeckTotalRating\x12\x0c\n\x04rank\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\r\x12\r\n\x05level\x18\x03 \x01(\r\x12\x14\n\x0clower_rating\x18\x04 \x01(\r\x12\x14\n\x0cupper_rating\x18\x05 \x01(\r\"\x82\x01\n\x12UserBandDeckRating\x12\x32\n\x0b\x64\x65\x63k_rating\x18\x01 \x03(\x0b\x32\x1d.krdori.pb2.ce.UserDeckRating\x12\x38\n\x0ctotal_rating\x18\x02 \x01(\x0b\x32\".krdori.pb2.ce.UserDeckTotalRating\"\xae\x01\n\x15UserBandDeckRatingMap\x12\x42\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x31.krdori.pb2.ce.UserBandDeckRatingMap.EntriesEntry\x1aQ\n\x0c\x45ntriesEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\x30\n\x05value\x18\x02 \x01(\x0b\x32!.krdori.pb2.ce.UserBandDeckRating:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'krdori.pb2.ce.user_deck_rating_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _USERBANDDECKRATINGMAP_ENTRIESENTRY._options = None
  _USERBANDDECKRATINGMAP_ENTRIESENTRY._serialized_options = b'8\001'
  _globals['_USERDECKRATING']._serialized_start=56
  _globals['_USERDECKRATING']._serialized_end=263
  _globals['_USERDECKTOTALRATING']._serialized_start=265
  _globals['_USERDECKTOTALRATING']._serialized_end=374
  _globals['_USERBANDDECKRATING']._serialized_start=377
  _globals['_USERBANDDECKRATING']._serialized_end=507
  _globals['_USERBANDDECKRATINGMAP']._serialized_start=510
  _globals['_USERBANDDECKRATINGMAP']._serialized_end=684
  _globals['_USERBANDDECKRATINGMAP_ENTRIESENTRY']._serialized_start=603
  _globals['_USERBANDDECKRATINGMAP_ENTRIESENTRY']._serialized_end=684
# @@protoc_insertion_point(module_scope)
