# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: krdori/pb2/ce/user_birthday_story.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'krdori/pb2/ce/user_birthday_story.proto\x12\rkrdori.pb2.ce\"O\n\x11UserBirthdayStory\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\x12\x19\n\x11\x62irthday_story_id\x18\x02 \x01(\r\x12\x0e\n\x06status\x18\x03 \x01(\t\"\xab\x01\n\x14UserBirthdayStoryMap\x12\x41\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x30.krdori.pb2.ce.UserBirthdayStoryMap.EntriesEntry\x1aP\n\x0c\x45ntriesEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12/\n\x05value\x18\x02 \x01(\x0b\x32 .krdori.pb2.ce.UserBirthdayStory:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'krdori.pb2.ce.user_birthday_story_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _USERBIRTHDAYSTORYMAP_ENTRIESENTRY._options = None
  _USERBIRTHDAYSTORYMAP_ENTRIESENTRY._serialized_options = b'8\001'
  _globals['_USERBIRTHDAYSTORY']._serialized_start=58
  _globals['_USERBIRTHDAYSTORY']._serialized_end=137
  _globals['_USERBIRTHDAYSTORYMAP']._serialized_start=140
  _globals['_USERBIRTHDAYSTORYMAP']._serialized_end=311
  _globals['_USERBIRTHDAYSTORYMAP_ENTRIESENTRY']._serialized_start=231
  _globals['_USERBIRTHDAYSTORYMAP_ENTRIESENTRY']._serialized_end=311
# @@protoc_insertion_point(module_scope)
