# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: krdori/pb2/ce/user_band_rank.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"krdori/pb2/ce/user_band_rank.proto\x12\rkrdori.pb2.ce\"\x9a\x01\n\x0cUserBandRank\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\x12\x0f\n\x07\x62\x61nd_id\x18\x02 \x01(\r\x12\x11\n\tband_rank\x18\x03 \x01(\r\x12\x0b\n\x03\x65xp\x18\x04 \x01(\r\x12\x0f\n\x07\x61\x64\x64_exp\x18\x05 \x01(\r\x12\x12\n\npooled_exp\x18\x06 \x01(\x04\x12\x11\n\ttotal_exp\x18\x07 \x01(\x04\x12\x10\n\x08next_exp\x18\x08 \x01(\r\"\x9c\x01\n\x0fUserBandRankMap\x12<\n\x07\x65ntries\x18\x01 \x03(\x0b\x32+.krdori.pb2.ce.UserBandRankMap.EntriesEntry\x1aK\n\x0c\x45ntriesEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12*\n\x05value\x18\x02 \x01(\x0b\x32\x1b.krdori.pb2.ce.UserBandRank:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'krdori.pb2.ce.user_band_rank_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _USERBANDRANKMAP_ENTRIESENTRY._options = None
  _USERBANDRANKMAP_ENTRIESENTRY._serialized_options = b'8\001'
  _globals['_USERBANDRANK']._serialized_start=54
  _globals['_USERBANDRANK']._serialized_end=208
  _globals['_USERBANDRANKMAP']._serialized_start=211
  _globals['_USERBANDRANKMAP']._serialized_end=367
  _globals['_USERBANDRANKMAP_ENTRIESENTRY']._serialized_start=292
  _globals['_USERBANDRANKMAP_ENTRIESENTRY']._serialized_end=367
# @@protoc_insertion_point(module_scope)
