# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: krdori/pb2/ce/user_action_set_album.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)krdori/pb2/ce/user_action_set_album.proto\x12\rkrdori.pb2.ce\"V\n\x12UserActionSetAlbum\x12\x15\n\raction_set_id\x18\x01 \x01(\r\x12\x14\n\x0c\x62\x61lloon_text\x18\x02 \x01(\t\x12\x13\n\x0bis_memorial\x18\x03 \x01(\x08\"\xae\x01\n\x15UserActionSetAlbumMap\x12\x42\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x31.krdori.pb2.ce.UserActionSetAlbumMap.EntriesEntry\x1aQ\n\x0c\x45ntriesEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\x30\n\x05value\x18\x02 \x01(\x0b\x32!.krdori.pb2.ce.UserActionSetAlbum:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'krdori.pb2.ce.user_action_set_album_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _USERACTIONSETALBUMMAP_ENTRIESENTRY._options = None
  _USERACTIONSETALBUMMAP_ENTRIESENTRY._serialized_options = b'8\001'
  _globals['_USERACTIONSETALBUM']._serialized_start=60
  _globals['_USERACTIONSETALBUM']._serialized_end=146
  _globals['_USERACTIONSETALBUMMAP']._serialized_start=149
  _globals['_USERACTIONSETALBUMMAP']._serialized_end=323
  _globals['_USERACTIONSETALBUMMAP_ENTRIESENTRY']._serialized_start=242
  _globals['_USERACTIONSETALBUMMAP_ENTRIESENTRY']._serialized_end=323
# @@protoc_insertion_point(module_scope)
