# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: krdori/pb2/ce/user_deco_pins_inventory.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,krdori/pb2/ce/user_deco_pins_inventory.proto\x12\rkrdori.pb2.ce\"P\n\x15UserDecoPinsInventory\x12\x0f\n\x07user_id\x18\x01 \x01(\r\x12\x14\n\x0c\x64\x65\x63o_pins_id\x18\x02 \x01(\r\x12\x10\n\x08quantity\x18\x03 \x01(\r\"\xb7\x01\n\x18UserDecoPinsInventoryMap\x12\x45\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x34.krdori.pb2.ce.UserDecoPinsInventoryMap.EntriesEntry\x1aT\n\x0c\x45ntriesEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\x33\n\x05value\x18\x02 \x01(\x0b\x32$.krdori.pb2.ce.UserDecoPinsInventory:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'krdori.pb2.ce.user_deco_pins_inventory_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _USERDECOPINSINVENTORYMAP_ENTRIESENTRY._options = None
  _USERDECOPINSINVENTORYMAP_ENTRIESENTRY._serialized_options = b'8\001'
  _globals['_USERDECOPINSINVENTORY']._serialized_start=63
  _globals['_USERDECOPINSINVENTORY']._serialized_end=143
  _globals['_USERDECOPINSINVENTORYMAP']._serialized_start=146
  _globals['_USERDECOPINSINVENTORYMAP']._serialized_end=329
  _globals['_USERDECOPINSINVENTORYMAP_ENTRIESENTRY']._serialized_start=245
  _globals['_USERDECOPINSINVENTORYMAP_ENTRIESENTRY']._serialized_end=329
# @@protoc_insertion_point(module_scope)
