# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: krdori/pb2/ce/user_backstage_talk_set.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+krdori/pb2/ce/user_backstage_talk_set.proto\x12\rkrdori.pb2.ce\"\xa5\x01\n\"UserBackstageTalkSetReadHistoryMap\x12O\n\x07\x65ntries\x18\x01 \x03(\x0b\x32>.krdori.pb2.ce.UserBackstageTalkSetReadHistoryMap.EntriesEntry\x1a.\n\x0c\x45ntriesEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'krdori.pb2.ce.user_backstage_talk_set_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _USERBACKSTAGETALKSETREADHISTORYMAP_ENTRIESENTRY._options = None
  _USERBACKSTAGETALKSETREADHISTORYMAP_ENTRIESENTRY._serialized_options = b'8\001'
  _globals['_USERBACKSTAGETALKSETREADHISTORYMAP']._serialized_start=63
  _globals['_USERBACKSTAGETALKSETREADHISTORYMAP']._serialized_end=228
  _globals['_USERBACKSTAGETALKSETREADHISTORYMAP_ENTRIESENTRY']._serialized_start=182
  _globals['_USERBACKSTAGETALKSETREADHISTORYMAP_ENTRIESENTRY']._serialized_end=228
# @@protoc_insertion_point(module_scope)
