# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: krdori/pb2/ce/user_situation.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"krdori/pb2/ce/user_situation.proto\x12\rkrdori.pb2.ce\"\xe1\x01\n\rUserSituation\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\x12\x14\n\x0csituation_id\x18\x02 \x01(\r\x12\r\n\x05level\x18\x03 \x01(\r\x12\x0b\n\x03\x65xp\x18\x04 \x01(\r\x12\x12\n\ncreated_at\x18\x05 \x01(\x04\x12\x0f\n\x07\x61\x64\x64_exp\x18\x06 \x01(\r\x12\x17\n\x0ftraining_status\x18\x07 \x01(\t\x12\x17\n\x0f\x64uplicate_count\x18\x08 \x01(\r\x12\x0e\n\x06illust\x18\t \x01(\t\x12\x11\n\tskill_exp\x18\n \x01(\r\x12\x13\n\x0bskill_level\x18\x0b \x01(\r\"\x9f\x01\n\x10UserSituationMap\x12=\n\x07\x65ntries\x18\x01 \x03(\x0b\x32,.krdori.pb2.ce.UserSituationMap.EntriesEntry\x1aL\n\x0c\x45ntriesEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12+\n\x05value\x18\x02 \x01(\x0b\x32\x1c.krdori.pb2.ce.UserSituation:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'krdori.pb2.ce.user_situation_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _USERSITUATIONMAP_ENTRIESENTRY._options = None
  _USERSITUATIONMAP_ENTRIESENTRY._serialized_options = b'8\001'
  _globals['_USERSITUATION']._serialized_start=54
  _globals['_USERSITUATION']._serialized_end=279
  _globals['_USERSITUATIONMAP']._serialized_start=282
  _globals['_USERSITUATIONMAP']._serialized_end=441
  _globals['_USERSITUATIONMAP_ENTRIESENTRY']._serialized_start=365
  _globals['_USERSITUATIONMAP_ENTRIESENTRY']._serialized_end=441
# @@protoc_insertion_point(module_scope)
