# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: krdori/pb2/ce/user_event_story.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$krdori/pb2/ce/user_event_story.proto\x12\rkrdori.pb2.ce\"P\n\x0eUserEventStory\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\x12\x10\n\x08\x65vent_id\x18\x02 \x01(\r\x12\x0b\n\x03seq\x18\x03 \x01(\r\x12\x0e\n\x06status\x18\x04 \x01(\t\"D\n\x12UserEventStoryList\x12.\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x1d.krdori.pb2.ce.UserEventStoryb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'krdori.pb2.ce.user_event_story_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USEREVENTSTORY']._serialized_start=55
  _globals['_USEREVENTSTORY']._serialized_end=135
  _globals['_USEREVENTSTORYLIST']._serialized_start=137
  _globals['_USEREVENTSTORYLIST']._serialized_end=205
# @@protoc_insertion_point(module_scope)
