# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: krdori/pb2/ce/user_comeback_status.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(krdori/pb2/ce/user_comeback_status.proto\x12\rkrdori.pb2.ce\"\x92\x01\n\x12UserComebackStatus\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\x12\x10\n\x08start_at\x18\x02 \x01(\x04\x12\x1f\n\x17live_boost_bonus_end_at\x18\x03 \x01(\x04\x12\x1d\n\x15\x63omeback_gacha_end_at\x18\x04 \x01(\x04\x12\x19\n\x11\x63omeback_gacha_id\x18\x05 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'krdori.pb2.ce.user_comeback_status_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USERCOMEBACKSTATUS']._serialized_start=60
  _globals['_USERCOMEBACKSTATUS']._serialized_end=206
# @@protoc_insertion_point(module_scope)
