# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: krdori/pb2/ce/user_stamp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1ekrdori/pb2/ce/user_stamp.proto\x12\rkrdori.pb2.ce\";\n\tUserStamp\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\x12\x10\n\x08stamp_id\x18\x02 \x01(\r\x12\x0b\n\x03seq\x18\x03 \x01(\r\"\x93\x01\n\x0cUserStampMap\x12\x39\n\x07\x65ntries\x18\x01 \x03(\x0b\x32(.krdori.pb2.ce.UserStampMap.EntriesEntry\x1aH\n\x0c\x45ntriesEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\'\n\x05value\x18\x02 \x01(\x0b\x32\x18.krdori.pb2.ce.UserStamp:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'krdori.pb2.ce.user_stamp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _USERSTAMPMAP_ENTRIESENTRY._options = None
  _USERSTAMPMAP_ENTRIESENTRY._serialized_options = b'8\001'
  _globals['_USERSTAMP']._serialized_start=49
  _globals['_USERSTAMP']._serialized_end=108
  _globals['_USERSTAMPMAP']._serialized_start=111
  _globals['_USERSTAMPMAP']._serialized_end=258
  _globals['_USERSTAMPMAP_ENTRIESENTRY']._serialized_start=186
  _globals['_USERSTAMPMAP_ENTRIESENTRY']._serialized_end=258
# @@protoc_insertion_point(module_scope)
