# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: krdori/pb2/ce/user_purchase_menu_last_visit.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1krdori/pb2/ce/user_purchase_menu_last_visit.proto\x12\rkrdori.pb2.ce\"Y\n\x19UserPurchaseMenuLastVisit\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\x12\x18\n\x10purchase_menu_id\x18\x02 \x01(\r\x12\x11\n\tupdate_at\x18\x03 \x01(\x04\"\xc3\x01\n\x1cUserPurchaseMenuLastVisitMap\x12I\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x38.krdori.pb2.ce.UserPurchaseMenuLastVisitMap.EntriesEntry\x1aX\n\x0c\x45ntriesEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\x37\n\x05value\x18\x02 \x01(\x0b\x32(.krdori.pb2.ce.UserPurchaseMenuLastVisit:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'krdori.pb2.ce.user_purchase_menu_last_visit_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _USERPURCHASEMENULASTVISITMAP_ENTRIESENTRY._options = None
  _USERPURCHASEMENULASTVISITMAP_ENTRIESENTRY._serialized_options = b'8\001'
  _globals['_USERPURCHASEMENULASTVISIT']._serialized_start=68
  _globals['_USERPURCHASEMENULASTVISIT']._serialized_end=157
  _globals['_USERPURCHASEMENULASTVISITMAP']._serialized_start=160
  _globals['_USERPURCHASEMENULASTVISITMAP']._serialized_end=355
  _globals['_USERPURCHASEMENULASTVISITMAP_ENTRIESENTRY']._serialized_start=267
  _globals['_USERPURCHASEMENULASTVISITMAP_ENTRIESENTRY']._serialized_end=355
# @@protoc_insertion_point(module_scope)
