# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: krdori/pb2/ce/user_practice_ticket.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(krdori/pb2/ce/user_practice_ticket.proto\x12\rkrdori.pb2.ce\"S\n\x12UserPracticeTicket\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\x12\x1a\n\x12practice_ticket_id\x18\x02 \x01(\r\x12\x10\n\x08quantity\x18\x03 \x01(\r\"L\n\x16UserPracticeTicketList\x12\x32\n\x07\x65ntries\x18\x01 \x03(\x0b\x32!.krdori.pb2.ce.UserPracticeTicketb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'krdori.pb2.ce.user_practice_ticket_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USERPRACTICETICKET']._serialized_start=59
  _globals['_USERPRACTICETICKET']._serialized_end=142
  _globals['_USERPRACTICETICKETLIST']._serialized_start=144
  _globals['_USERPRACTICETICKETLIST']._serialized_end=220
# @@protoc_insertion_point(module_scope)
