# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: krdori/pb2/ce/user_deco_frame_inventory.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-krdori/pb2/ce/user_deco_frame_inventory.proto\x12\rkrdori.pb2.ce\"O\n\x16UserDecoFrameInventory\x12\x0f\n\x07user_id\x18\x01 \x01(\r\x12\x15\n\rdeco_frame_id\x18\x02 \x01(\r\x12\r\n\x05level\x18\x03 \x01(\r\"\xba\x01\n\x19UserDecoFrameInventoryMap\x12\x46\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x35.krdori.pb2.ce.UserDecoFrameInventoryMap.EntriesEntry\x1aU\n\x0c\x45ntriesEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\x34\n\x05value\x18\x02 \x01(\x0b\x32%.krdori.pb2.ce.UserDecoFrameInventory:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'krdori.pb2.ce.user_deco_frame_inventory_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _USERDECOFRAMEINVENTORYMAP_ENTRIESENTRY._options = None
  _USERDECOFRAMEINVENTORYMAP_ENTRIESENTRY._serialized_options = b'8\001'
  _globals['_USERDECOFRAMEINVENTORY']._serialized_start=64
  _globals['_USERDECOFRAMEINVENTORY']._serialized_end=143
  _globals['_USERDECOFRAMEINVENTORYMAP']._serialized_start=146
  _globals['_USERDECOFRAMEINVENTORYMAP']._serialized_end=332
  _globals['_USERDECOFRAMEINVENTORYMAP_ENTRIESENTRY']._serialized_start=247
  _globals['_USERDECOFRAMEINVENTORYMAP_ENTRIESENTRY']._serialized_end=332
# @@protoc_insertion_point(module_scope)
