# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: krdori/pb2/ce/user_miracle_ticket_exchanges.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1krdori/pb2/ce/user_miracle_ticket_exchanges.proto\x12\rkrdori.pb2.ce\"\xa3\x01\n!UserMiracleTicketExchangeCountMap\x12N\n\x07\x65ntries\x18\x01 \x03(\x0b\x32=.krdori.pb2.ce.UserMiracleTicketExchangeCountMap.EntriesEntry\x1a.\n\x0c\x45ntriesEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\r:\x02\x38\x01\"\xaa\x01\n\x1aUserMiracleTicketExchanges\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\x12\x19\n\x11miracle_ticket_id\x18\x02 \x01(\r\x12`\n&user_miracle_ticket_exchange_count_map\x18\x03 \x01(\x0b\x32\x30.krdori.pb2.ce.UserMiracleTicketExchangeCountMap\"\xc6\x01\n\x1dUserMiracleTicketExchangesMap\x12J\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x39.krdori.pb2.ce.UserMiracleTicketExchangesMap.EntriesEntry\x1aY\n\x0c\x45ntriesEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\x38\n\x05value\x18\x02 \x01(\x0b\x32).krdori.pb2.ce.UserMiracleTicketExchanges:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'krdori.pb2.ce.user_miracle_ticket_exchanges_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _USERMIRACLETICKETEXCHANGECOUNTMAP_ENTRIESENTRY._options = None
  _USERMIRACLETICKETEXCHANGECOUNTMAP_ENTRIESENTRY._serialized_options = b'8\001'
  _USERMIRACLETICKETEXCHANGESMAP_ENTRIESENTRY._options = None
  _USERMIRACLETICKETEXCHANGESMAP_ENTRIESENTRY._serialized_options = b'8\001'
  _globals['_USERMIRACLETICKETEXCHANGECOUNTMAP']._serialized_start=69
  _globals['_USERMIRACLETICKETEXCHANGECOUNTMAP']._serialized_end=232
  _globals['_USERMIRACLETICKETEXCHANGECOUNTMAP_ENTRIESENTRY']._serialized_start=186
  _globals['_USERMIRACLETICKETEXCHANGECOUNTMAP_ENTRIESENTRY']._serialized_end=232
  _globals['_USERMIRACLETICKETEXCHANGES']._serialized_start=235
  _globals['_USERMIRACLETICKETEXCHANGES']._serialized_end=405
  _globals['_USERMIRACLETICKETEXCHANGESMAP']._serialized_start=408
  _globals['_USERMIRACLETICKETEXCHANGESMAP']._serialized_end=606
  _globals['_USERMIRACLETICKETEXCHANGESMAP_ENTRIESENTRY']._serialized_start=517
  _globals['_USERMIRACLETICKETEXCHANGESMAP_ENTRIESENTRY']._serialized_end=606
# @@protoc_insertion_point(module_scope)
