# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: krdori/pb2/ce/user_home_banner.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$krdori/pb2/ce/user_home_banner.proto\x12\rkrdori.pb2.ce\"(\n\x0eUserHomeBanner\x12\x16\n\x0ehome_banner_id\x18\x01 \x01(\r\"D\n\x12UserHomeBannerList\x12.\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x1d.krdori.pb2.ce.UserHomeBannerb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'krdori.pb2.ce.user_home_banner_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USERHOMEBANNER']._serialized_start=55
  _globals['_USERHOMEBANNER']._serialized_end=95
  _globals['_USERHOMEBANNERLIST']._serialized_start=97
  _globals['_USERHOMEBANNERLIST']._serialized_end=165
# @@protoc_insertion_point(module_scope)
