# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: krdori/pb2/ce/user_stage_challenge.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(krdori/pb2/ce/user_stage_challenge.proto\x12\rkrdori.pb2.ce\"\x84\x01\n\x19UserStageChallengeStageNo\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\x12\x1a\n\x12stage_challenge_id\x18\x02 \x01(\r\x12 \n\x18stage_challenge_stage_no\x18\x03 \x01(\r\x12\x18\n\x10\x61\x63hivement_count\x18\x04 \x01(\r\"Z\n\x1dUserStageChallengeStageNoList\x12\x39\n\x07\x65ntries\x18\x01 \x03(\x0b\x32(.krdori.pb2.ce.UserStageChallengeStageNo\"\xc7\x01\n\x1cUserStageChallengeStageNoMap\x12I\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x38.krdori.pb2.ce.UserStageChallengeStageNoMap.EntriesEntry\x1a\\\n\x0c\x45ntriesEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12;\n\x05value\x18\x02 \x01(\x0b\x32,.krdori.pb2.ce.UserStageChallengeStageNoList:\x02\x38\x01\"o\n\x12UserStageChallenge\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\x12\x1a\n\x12stage_challenge_id\x18\x02 \x01(\r\x12\x0b\n\x03seq\x18\x03 \x01(\r\x12\x1f\n\x17total_achievement_count\x18\x04 \x01(\r\"\xae\x01\n\x15UserStageChallengeMap\x12\x42\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x31.krdori.pb2.ce.UserStageChallengeMap.EntriesEntry\x1aQ\n\x0c\x45ntriesEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\x30\n\x05value\x18\x02 \x01(\x0b\x32!.krdori.pb2.ce.UserStageChallenge:\x02\x38\x01\"\x96\x01\n\x17UserStageChallengeScore\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\x12\x1a\n\x12stage_challenge_id\x18\x02 \x01(\r\x12 \n\x18stage_challenge_stage_no\x18\x03 \x01(\r\x12\x18\n\x10music_difficulty\x18\x04 \x01(\t\x12\x12\n\nhigh_score\x18\x05 \x01(\r\"V\n\x1bUserStageChallengeScoreList\x12\x37\n\x07\x65ntries\x18\x01 \x03(\x0b\x32&.krdori.pb2.ce.UserStageChallengeScore\"\xc1\x01\n\x1aUserStageChallengeScoreMap\x12G\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x36.krdori.pb2.ce.UserStageChallengeScoreMap.EntriesEntry\x1aZ\n\x0c\x45ntriesEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\x39\n\x05value\x18\x02 \x01(\x0b\x32*.krdori.pb2.ce.UserStageChallengeScoreList:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'krdori.pb2.ce.user_stage_challenge_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _USERSTAGECHALLENGESTAGENOMAP_ENTRIESENTRY._options = None
  _USERSTAGECHALLENGESTAGENOMAP_ENTRIESENTRY._serialized_options = b'8\001'
  _USERSTAGECHALLENGEMAP_ENTRIESENTRY._options = None
  _USERSTAGECHALLENGEMAP_ENTRIESENTRY._serialized_options = b'8\001'
  _USERSTAGECHALLENGESCOREMAP_ENTRIESENTRY._options = None
  _USERSTAGECHALLENGESCOREMAP_ENTRIESENTRY._serialized_options = b'8\001'
  _globals['_USERSTAGECHALLENGESTAGENO']._serialized_start=60
  _globals['_USERSTAGECHALLENGESTAGENO']._serialized_end=192
  _globals['_USERSTAGECHALLENGESTAGENOLIST']._serialized_start=194
  _globals['_USERSTAGECHALLENGESTAGENOLIST']._serialized_end=284
  _globals['_USERSTAGECHALLENGESTAGENOMAP']._serialized_start=287
  _globals['_USERSTAGECHALLENGESTAGENOMAP']._serialized_end=486
  _globals['_USERSTAGECHALLENGESTAGENOMAP_ENTRIESENTRY']._serialized_start=394
  _globals['_USERSTAGECHALLENGESTAGENOMAP_ENTRIESENTRY']._serialized_end=486
  _globals['_USERSTAGECHALLENGE']._serialized_start=488
  _globals['_USERSTAGECHALLENGE']._serialized_end=599
  _globals['_USERSTAGECHALLENGEMAP']._serialized_start=602
  _globals['_USERSTAGECHALLENGEMAP']._serialized_end=776
  _globals['_USERSTAGECHALLENGEMAP_ENTRIESENTRY']._serialized_start=695
  _globals['_USERSTAGECHALLENGEMAP_ENTRIESENTRY']._serialized_end=776
  _globals['_USERSTAGECHALLENGESCORE']._serialized_start=779
  _globals['_USERSTAGECHALLENGESCORE']._serialized_end=929
  _globals['_USERSTAGECHALLENGESCORELIST']._serialized_start=931
  _globals['_USERSTAGECHALLENGESCORELIST']._serialized_end=1017
  _globals['_USERSTAGECHALLENGESCOREMAP']._serialized_start=1020
  _globals['_USERSTAGECHALLENGESCOREMAP']._serialized_end=1213
  _globals['_USERSTAGECHALLENGESCOREMAP_ENTRIESENTRY']._serialized_start=1123
  _globals['_USERSTAGECHALLENGESCOREMAP_ENTRIESENTRY']._serialized_end=1213
# @@protoc_insertion_point(module_scope)
