# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: krdori/pb2/ce/user_daily_live_total_reward_history.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n8krdori/pb2/ce/user_daily_live_total_reward_history.proto\x12\rkrdori.pb2.ce\"\x93\x01\n\x1fUserDailyLiveTotalRewardHistory\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\x12\x15\n\rdaily_live_id\x18\x02 \x01(\r\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x18\n\x10\x64\x61ily_live_count\x18\x04 \x01(\r\x12\x1e\n\x16\x64\x61ily_live_clear_count\x18\x05 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'krdori.pb2.ce.user_daily_live_total_reward_history_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USERDAILYLIVETOTALREWARDHISTORY']._serialized_start=76
  _globals['_USERDAILYLIVETOTALREWARDHISTORY']._serialized_end=223
# @@protoc_insertion_point(module_scope)
