# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: krdori/pb2/ce/user_story_event.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from krdori.pb2.ce import user_event_story_pb2 as krdori_dot_pb2_dot_ce_dot_user__event__story__pb2
from krdori.pb2.ce import master_player_resource_pb2 as krdori_dot_pb2_dot_ce_dot_master__player__resource__pb2
from krdori.pb2.ce import newly_opened_content_pb2 as krdori_dot_pb2_dot_ce_dot_newly__opened__content__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$krdori/pb2/ce/user_story_event.proto\x12\rkrdori.pb2.ce\x1a$krdori/pb2/ce/user_event_story.proto\x1a*krdori/pb2/ce/master_player_resource.proto\x1a(krdori/pb2/ce/newly_opened_content.proto\"\x93\x02\n\x1fUserStoryEventReadStoryResponse\x12<\n\x15read_user_event_story\x18\x01 \x01(\x0b\x32\x1d.krdori.pb2.ce.UserEventStory\x12\x32\n\x07rewards\x18\x02 \x01(\x0b\x32!.krdori.pb2.ce.PlayerResourceList\x12\x44\n\x15newly_opened_contents\x18\x03 \x01(\x0b\x32%.krdori.pb2.ce.NewlyOpenedContentList\x12\x1a\n\x12recommend_story_id\x18\x04 \x01(\r\x12\x1c\n\x14recommend_story_type\x18\x05 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'krdori.pb2.ce.user_story_event_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USERSTORYEVENTREADSTORYRESPONSE']._serialized_start=180
  _globals['_USERSTORYEVENTREADSTORYRESPONSE']._serialized_end=455
# @@protoc_insertion_point(module_scope)
