# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: krdori/pb2/ce/user_bad_penalty.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$krdori/pb2/ce/user_bad_penalty.proto\x12\rkrdori.pb2.ce\"\\\n\x0eUserBadPenalty\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\x12\x11\n\tbad_count\x18\x02 \x01(\r\x12\x10\n\x08\x62\x61\x64_date\x18\x03 \x01(\x04\x12\x14\n\x0cpenalty_date\x18\x04 \x01(\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'krdori.pb2.ce.user_bad_penalty_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USERBADPENALTY']._serialized_start=55
  _globals['_USERBADPENALTY']._serialized_end=147
# @@protoc_insertion_point(module_scope)
