# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: krdori/pb2/ce/user_generic_animation.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*krdori/pb2/ce/user_generic_animation.proto\x12\rkrdori.pb2.ce\"U\n\x14UserGenericAnimation\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\x12\x1c\n\x14generic_animation_id\x18\x02 \x01(\r\x12\x0e\n\x06status\x18\x03 \x01(\t\"\xb4\x01\n\x17UserGenericAnimationMap\x12\x44\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x33.krdori.pb2.ce.UserGenericAnimationMap.EntriesEntry\x1aS\n\x0c\x45ntriesEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\x32\n\x05value\x18\x02 \x01(\x0b\x32#.krdori.pb2.ce.UserGenericAnimation:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'krdori.pb2.ce.user_generic_animation_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _USERGENERICANIMATIONMAP_ENTRIESENTRY._options = None
  _USERGENERICANIMATIONMAP_ENTRIESENTRY._serialized_options = b'8\001'
  _globals['_USERGENERICANIMATION']._serialized_start=61
  _globals['_USERGENERICANIMATION']._serialized_end=146
  _globals['_USERGENERICANIMATIONMAP']._serialized_start=149
  _globals['_USERGENERICANIMATIONMAP']._serialized_end=329
  _globals['_USERGENERICANIMATIONMAP_ENTRIESENTRY']._serialized_start=246
  _globals['_USERGENERICANIMATIONMAP_ENTRIESENTRY']._serialized_end=329
# @@protoc_insertion_point(module_scope)
